### ISSUE TITLE
Wrong git commands for Level 7

### ISSUE THREAD

**Issue by Lin-Shuang-Shuang** [nus-cs2103-AY2324S2/forum#101]
I mistakenly keyed in wrong commands when pushing my level 7 code.

(On branch branch-Level-7)
1. git add -A
2. git commit -m "..."
3. git merge master
4. git checkout master
5. git tag -a Level-7
6. git push origin master   
7. git push -u origin branch-Level-7
8. git push origin Level-7 

May I know how I can correct my mistake?

**Comment by damithc** [comment]
@Lin-Shuang-Shuang How does your revision graph looks now? Perhaps share a screenshot? Even if you are using CLI to perform Git operations, you can still use a GUI such as Sourcetree to get a more visual view of the current status.

**Comment by aureliony** [comment]
Looking at your commit history, you merged from the master branch into branch-Level-7 instead of the other way. However, this merge did not do anything as the master branch was unmodified since the branch was created.

Hence, you need to merge branch-Level-7 into master and override the incorrect tag by passing -f into git tag:
```
git checkout master
git merge --no-ff branch-Level-7
git tag Level-7 -f
git push origin master
git push origin Level-7
```

**Comment by Lin-Shuang-Shuang** [comment]
@aureliony This helped! Thank you!

**Comment by damithc** [comment]
Thanks for the help @aureliony 💯
