### ISSUE TITLE
Practice exam part 2 sequence diagram

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#1050]
For this question
<img width="400" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/b21a9c22-36d1-4538-99e6-495b7d327075">

I'm trying to understand why the activation bar for init is within the activation bar for the client constructor (and why init and the constructor don't have separate activation bars) whereas the activation bars for add and set are separate

<img width="400" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/c17ebb06-ca20-4f3f-bfca-8cd3cfeec371">

Can I check if my reasoning is correct:
The client constructor is still in use and hasn't been returned throughout the time init is called so the activation bar for init is within the activation bar for the client constructor
But for the add and set methods, their execution is separate. Since the activation bar should be unbroken until the method is returned, once one method returns, the activation bar can be broken and a new one is created for the other method

**Comment by yuechen2001** [comment]
Yep i think your reasoning is correct. Basically the constructor for Client only returns after the execution of `s.set(port)`, hence the activation bar remains unbroken until the 2 parallel-executed methods return. 
The reason why init is within the constructor activation bar is because it is called upon within the constructor (and before it returns), hence it's considered a method of Client object calling another method of the same object, therefore the two activation boxes are stacked ontop of each other.

**Comment by sindhurajain** [comment]
Thanks!
