### ISSUE TITLE
Why is constructor activation bar not provided?

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#1054]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/6c6e0bfc-6686-4950-8c42-cd92bf6bd490)

Why is the constructor of C not provided given that its created when the method is called below
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/354cba09-a5b3-4d3b-b2ed-a8ab31b40f2e)

**Comment by baskargopinath** [comment]
activation bar is optional but showing that s exists before c is not

**Comment by justincred** [comment]
does this only apply when creating the object as the function is pointed to the box containing the class name so it has to be positioned lower?

**Comment by justincred** [comment]
like for example, in here its the same level 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/cf8787e0-572e-46d7-b7b7-dcbecf780fe0)

**Comment by jinhanfromNUS** [comment]
Umm, you may say that.

Personally, I fell that another way to say it more accurately is, due to the creation of Client object `c` is later than Server object `s`, so it needs to be positioned lower than `s`.

If there are two object creations, let's say `a` and `b` where `a` is created before `b`, then it `b` shall be positioned lower than `a`.

The reason why `s` is positioned higher than `c` is because `s` already existed before `c` is created.

**Comment by damithc** [comment]
> Personally, I fell that another way to say it more accurately is, due to the creation of Client object `c` is later than Server object `s`, so it needs to be positioned lower than `s`.
> 
> If there are two object creations, let's say `a` and `b` where `a` is created before `b`, then it `b` shall be positioned lower than `a`.
> 
> The reason why `s` is positioned higher than `c` is because `s` already existed before `c` is created.

Yup. Everything  that existed at the start should appear at the top, at the same level.
Anything that was created during the interaction should appear lower, in order they were created (created later means positioned lower). This is because time flows in the downward direction.

**Comment by justincred** [comment]
thanks!
