### ISSUE TITLE
One file per model

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#110]
Is it alright to have one file for each model? e.g.todos.txt, events.txt, deadlines.txt?

**Comment by damithc** [comment]
@tankh99 No restrictions from our side. So, consider it as an opportunity to make a design decision yourself, after considering cost and benefits, from both developer and user point of view. Getting better at making such decisions is an intended learning outcome of this course. Feel free to discuss such decisions here in the forum too, so that others can benefit from it too.

**Comment by drustanyjt** [comment]
@tankh99 I think a drawback of splitting save data into multiple files is if these files need to be shared with others, you would need to transfer multiple files over instead of just one. Was there some benefit you saw in having one file per model?

**Comment by tankh99** [comment]
> @tankh99 I think a drawback of splitting save data into multiple files is if these files need to be shared with others, you would need to transfer multiple files over instead of just one. Was there some benefit you saw in having one file per model?

Hi, I find that splitting into multiple files removes the need to be able to identify what kind of task each row is. And it simplifies the file parsing as well

**Comment by yisiox** [comment]
Hi @tankh99, I too am inclined towards keeping them in the same file for consideration of code complexity and potential points of failure. Since we will have to perform more file IO operations, I thought that multiple files may give rise to a situation whereby data is desynchronized if say one of three write operations fail. Suppose it is the last write operation that failed, I'd then have decide if I should undo the previous two writes. Also if new types of tasks were required in future it might be harder to refactor.

Using the `split` method of strings to read from files like `String[] taskInfo = line.split(",")` has worked well for me as regular expressions are quite robust, but a conditional switch is still necessary to choose the type of task to instantiate. I'm also thinking it can be used in some cases to handle cases where the user enters extraneous whitespaces also to guard against weird formatting when saving it to the disk. In example, for taking input from the user,
```java
String[] command = sc.nextLine().split("\\s+(/(from|to|by)\\s+)?");
```
and something similar may be able to recover from extraneous characters when reading from the file.

That said, I do see advantages for keeping the files separate in that it's easier to recover from a corrupted task type, and storage could be optimized for each type of task or have specialized handling of each type, and error handling is more readable for more specialized code. 

Maybe there could be some middle ground like storing the different types together in a file but creating handlers for each new type as separate classes or files. It does seem overly ambitious though as it's mostly to accommodate adding of new types without guarantee that it will be a requirement. If anyone has any thoughts on this, do advise.

**Comment by tankh99** [comment]
> Hi @tankh99, I too am inclined towards keeping them in the same file for consideration of code complexity and potential points of failure. Since we will have to perform more file IO operations, I thought that multiple files may give rise to a situation whereby data is desynchronized if say one of three write operations fail. Suppose it is the last write operation that failed, I'd then have decide if I should undo the previous two writes. Also if new types of tasks were required in future it might be harder to refactor.

Regarding this, I don't believe there are multiple write operations are required by the iP right now? 

But I do see where you're coming from. It's a more personal choice to not want to customise the application specifically just for tasks, which are related to each other. In case other models that don't inherit from tasks also need to be added in the application, it is okay to refactor

**Comment by yisiox** [comment]
I do agree now that it's more so personal choice depending on how futureproof / how you anticipate the project to evolve. 

I ended up going for the factory design pattern - using a factory class to create and return the different subclasses of `Task`. This makes it so that I can easily extend the code in case of new types of tasks (also did the same for logic, which it has helped since the iP increments tend to add new commands, minimizing the code I have to change) as all other classes only ever see the `Task` type instead of the specific subclass. Also solved a circular dependency issue which I had between the `Parser` and `Task`.
