### ISSUE TITLE
Duke A-TextUiTesting: Automated Text UI Testing: Error

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#122]
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at Duke.main(Duke.java:14)
        
I'm running bat for Windows but I'm getting this error. Can I know what did you guys do to fix it?

Thank you for your help!

**Comment by tituschewxj** [comment]
`nextLine()` throws a `NoSuchElementException` if no line was found. This means that `nextLine()` tries to read the next line from the `input.txt` file, but doesn't find a line.

To fix this, you can add the your command to exit, `bye`, as the last line of your `input.txt` file, so that `nextLine()` isn't called when there is no next line in your `input.txt`.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Additionally, remember to end your each command with a newline character to ensure that the command is read into the program.

**Comment by Darkarche3** [comment]
I managed to solve it. Thanks for all the help!
