### ISSUE TITLE
Error while merging branch

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#125]
I am getting the following error when merging my branch-Level-7 to master:

git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks merge branch-Level-7
Updating 768732f..5acb765
error: The following untracked working tree files would be overwritten by merge:
	data/logfile.txt
Please move or remove them before you merge.
Aborting

Completed with errors, see above.

It is maybe due to my logfile.txt which is basically the file that gets created in Level-7. How do I remove this file, I have so far committed and pushed all the file in my branch-Level-7 but am not able to merge.

**Comment by itstrueitstrueitsrealitsreal** [comment]
I'm writing this with the assumption that the logfile is used to store tasks in your list locally, and in that case, you can .gitignore the file and try merging the branches again?

**Comment by guanquann** [comment]
`error: The following untracked working tree files would be overwritten by merge:`

means that there is some file in your directory that is not committed. In this case, your current branch data/logfile.txt has been edited, while the branch you are trying to merge from has another data/logfile.txt. Since this is not an important file, you can add it to .gitignore, or simply delete this file and merge.

**Comment by radeon2525** [comment]
Alright I understood, thank you.
