### ISSUE TITLE
Level 7 - saving to local file

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#160]
from what i understand, when starting up our chatbot, we just load whatever tasks are inside chatbot.txt to our list of todo items and when done modifying the list we just write the new list into the chatbot.txt before exiting. we dont need to adjust chatbot.txt in real time as we remove or add or modify items right?

**Comment by damithc** [comment]
@bgopi23 There is no specific requirement from our side. So, consider it as an opportunity to make a design decision yourself, after considering cost and benefits, from both developer and user point of view. Getting better at making such decisions is an intended learning outcome of this course. Feel free to discuss such decisions here in the forum too, so that others can benefit from it too.

**Comment by baskargopinath** [comment]
okay prof @damithc
