### ISSUE TITLE
A-Gradle

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#187]
i haven't merged add-gradle-support to my master branch.

i see 2 branches

> 
> **_1) origin/add-gradle-support
> 2) upstream/add-gradle-support_**
> 

which one do i use to merge into my master branch? and why is there 2

**Comment by fy17ohhh** [comment]
upstream refers to the original repo that you have forked,
you have the upstream repo because you followed this instruction
<img width="823" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/f46c9464-c336-4020-b4d4-0ef3b13fdd21">

origin is your own fork, i.e. your own repo on GitHub, clone of the original repo of GitHub

**Comment by baskargopinath** [comment]
@fy17ohhh i didnt do that tho and still have both branches. anyway which repo should i merge my master to?

**Comment by ZHANGTIANYAO1** [comment]
@bgopi23  I think is the first one
`1) origin/add-gradle-support`

**Comment by fy17ohhh** [comment]
> @fy17ohhh i didnt do that tho and still have both branches. anyway which repo should i merge my master to?

Since you are working on your own fork and will push the merge to your own remote branch, should be the first one

**Comment by baskargopinath** [comment]
thanks @fy17ohhh @ZHANGTIANYAO1
