### ISSUE TITLE
Week 3 Quiz Question on Text Wrapping

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#199]
Q: When wrapping a long statement (an example given below), one should indent lines using two tabs instead of the usual one tab.
A: False 

Can someone explain why?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/133e50df-e5f5-4c0c-be14-9b141143adba)

**Comment by dillontkh** [comment]
Indentation for wrapped lines should be 8 _spaces_. Indenting using 1 tab character is not the same as using 4 spaces.

**Comment by UdhayaShan1** [comment]
We should not be using tabs as our metric regardless of whether it does 4 or 8 spaces correctly.

**Comment by damithc** [comment]
Good responses so far, @dillontkh @UdhayaShan1 
Can someone also elaborate why tabs should not be used in place of spaces (wouldn't the end result be the same)?

**Comment by yisiox** [comment]
I think the key here is to recognize that we are familiar with our editors expanding our tab input as some number of spaces, but tabs as actual tab characters is different from whitespaces. 

The arguments for using spaces instead of tabs would be suppose you had to wrap a line but line up function parameters, it is likely tabs and spaces need to be mixed to align it exactly. Yet tab widths could differ from device to device, so it may look different when transferred to another device. For languages like python where indentation matters, mixing of tabs and spaces could lead to errors, and may not be easy to visually catch. Spaces are also more consistent when copied over to e.g. forums, the web. So overall, tabs tend to require spaces on top of tabs anyways, and spaces are more robust.

**Comment by billyhoce** [comment]
Thanks everyone! Will be closing this thread.

**Comment by damithc** [comment]
Good points @yisiox 
To add...
* The course doesn't mean to say spaces are better than tabs. The developer world is divided on that, with no clear answer. However, it is important to select and stick with one (in our case, we have chosen spaces) and not mix the two. If we do, the code will look messed up when viewed through a tool that uses a different number of spaces for the tab compared to the tool used to write the code. A good example is, IntelliJ shows a tab as 4 spaces while GitHub shows a tab as 8 spaces.
* IntelliJ (and probably other IDEs) can be configured to auto-convert tabs to spaces. So, you can continue to type a tab (if you are used to using tabs) but the IDE will automatically replace it with a specific number of spaces (you can specify how many -- in our case, should be 4).
