### ISSUE TITLE
Week 4 content: Book - Chapter - Shelf example

### ISSUE THREAD

**Issue by sun-ruiheng** [nus-cs2103-AY2324S2/forum#207]
Just wondering if there's a fundamental difference between:
1. drawing the composition diamond, and
2. indicating multiplicity of 1, i.e. each Chapter is linked to no more, no less than 1 Book
Is it just clearer visually to have the diamonds, but fundamentally they are the same?

Similarly for aggregation.

**Comment by UdhayaShan1** [comment]
Do you mean writing multiplicity instead of composition diamond? If so, I don't think that's possible because that would create some sort of cyclic relationship, i.e Chapter having Book fields in its class

**Comment by sun-ruiheng** [comment]
@UdhayaShan1 Thanks for your input!

Would we lose the composition relationship if Chapter has a Book field in its class?

If so, how do we ensure Chapter is never defined outside of Book, without having a field like this? 🤔

**Comment by UdhayaShan1** [comment]
Sflr

The more I think about it, I get confused haha. By definition there is no cyclical link, so for your question, I think its possible if we are not referring to them as in Parent-Child cyclical relationship. Chapter can have book field but the same book can have multiple chapter fields but may not necessarily refer in a parent-child relationship.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/59b57fb6-1a83-4aec-b867-8e9c4e05acea)

Suppose this from the tutorial, composition by definition cannot have cyclical links but here it is implied Category is made out of possibly several books, but each book can be made up of several chapters.

**Comment by UdhayaShan1** [comment]
For above I think below code represents it..,

```ruby
class Chapter {
    #Signals composition, there is deletion effect as well
    public Book[] listOfBooks = new Book[5];
    
}


class Book {
    #Nothing to do with composition relationship. Just that this book has many chapters.
    public Chapter[] listOfChapters = new Chapter[10];
}
```

If anyone can weigh in on what is meant by cyclical, that would be great!

**Comment by damithc** [comment]
Sorry folks, it took me longer than intended to chime in.

> * drawing the composition diamond, and
> * indicating multiplicity of 1, i.e. each Chapter is linked to no more, no less than 1 Book
>   Is it just clearer visually to have the diamonds, but fundamentally they are the same?

While composition results in a multiplicity of exactly 1, the reverse is not always true (you can have a multiplicity of 1 which is not a composition). So, they are not equivalent.

> Would we lose the composition relationship if Chapter has a Book field in its class?

Which class has a field of which class is matter of _navigability_ (not related to composition). It is possible to have the navigability in the direction `Book ---> Chapter` i.e., the Book has a field to track Chapters, or the reverse direction ( `Book <---- Chapter` i.e., Chapter has a field to track the Book) or both directions (`Book <----> Chapter` i.e., both classes track each other). In all three cases, the fact remains that the relationship is composition simply because Book and Chapters have a _part-of_ relationship.

> how do we ensure Chapter is never defined outside of Book, without having a field like this?

More generally, _how would the implementation enforce semantics defined in the model?_ This depends on the implementation language and tools. For example, it is possible that there is a separate tool that monitors objects at runtime and prevents creating objects in incorrect ways. Or one can simply do intensive code reviews to ensure the code doesn't create Chapter objects outside of Book objects.
Similarly, it is up to the implementation to prevent cyclical links where there shouldn't be cyclical links.
Also, keep in mind that there is not 1-to-1 mapping between UML and Java. A Java implementation of a UML class diagram might not enforce all the semantics defined in the class diagram simply because Java doesn't have the mechanisms to implement certain semantics. For example, the class diagram might indicate that A cannot exist without B and B cannot exist without A, but Java doesn't have a way to create two objects at the same time which means either A or B must exist briefly on its own until we create the second object.
