### ISSUE TITLE
[Impending long question] Query regarding linking logic between bot and UI

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#218]
Hi all, the current query I have now is that I am unable to see the link between the bot and the UI. Let me provide the context followed by my question. 

[Context] So in my bot java file, I have a `main()` method which builds an instance of my bot and calls the `run()`, which triggers the series of events within my `run()` method such as reading in the user's input, parsing and making sense of them and print the according response.

[Question] So with the GUI involved now, do I move the logic of my `run()` method into my 'getResponse(String input)' (as per part 4 of the GUI tutorial) and remove the original `run()` method? 

[Question 2] I don't really see how the `main()` method in my bot java file is being run since the Launcher class will run the Main.java file (as per part 4 of the GUI tutorial) which instantiates an instance of my bot WITH the empty constructor (as per the part 1 of the GUI tutorial). If that is the case, the original constructor of the bot class (which requires the passing in of the file path, as per the guidance from A-OOP) would never be called, then how does the application run?

**Comment by camille-readbean** [comment]
One possible way is to think of the GUI as an extension of your UI. In a way the commands entered can still be passed to the inner "app". Just that its no longer doing prints to stdout.  
  
Edit:  
So yes, you can move the logic or run into getResponse or wrap getResponse around run, so maybe like a 

```java
void getResponse(String input) {
    run(input);
}
```

**Comment by damithc** [comment]
@cheahTJ You can also explore the iP code of those who posted in https://github.com/nus-cs2103-AY2324S2/forum/issues/215 
 to see how they connected their GUI to the logic (i.e., go to their iP repos, view their PR [here](https://github.com/nus-cs2103-AY2324S2/ip/pulls) or view their code via the [ip code dashboard](https://nus-cs2103-ay2324s2.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt&since=2024-01-19))

**Comment by cheahTJ** [comment]
Thank you prof @damithc  and @camille-readbean, I could see the link :)
