### ISSUE TITLE
Custom exception handling 

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#219]
Hi, I would like to know more about the point of having to create the custom exception class Duke Exception, what really is the point of doing so if for example, in loading a file, a FileNotFound Exception is thrown, isn't it possible to just throw the error in the method such as 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/0b23f849-51f2-4d9d-8f4b-0f0f1791d124)
instead of for example doing 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/7e8a63d3-1bee-40c9-bd34-0680db40c1c0)
where you instead throw the duke exception, shouldn't the duke exception only be used for custom and special scenarios? 
Also in the picture above, if im not wrong, the tasks = new TaskList(); is for when the chatbot is newly created and the data file has yet to been created, however why is it in the catch block instead and also alongside a Ui showing error when it's not really an error? Wouldn't an if-else statement be more suitable for such control flows? Thank you for answering my questions

**Comment by UdhayaShan1** [comment]
Closely related to #210 , made some points there too along with rest

**Comment by damithc** [comment]
Error handling best practices are a good topic to discuss, although some aspects of it is subjective (i.e.,  opinion-based) So, thanks @justincred for raising this. Others are encouraged to pitch in with your inputs.

In the meantime, some inputs from me:
* The given code is an example only. You are free to deviate. 
* It is fine (and in fact good to) reuse existing exceptions when they match the situation, rather than create your own.
* In the given code, it is likely the line 11 is throwing a `DukeException` only when something exceptional happens. For example, if the file is not yet created, it need not throw an exception but if the file is corrupted, it can throw the exception. So, the `DukeException` indicates that a Duke-specific error happened, and likely contains Duke-specific information the UI can use when displaying the error to the user (if we tweak line 13 as `ui.showLoadingError(e);`).

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/5b46e5dd-c9eb-4d69-b4ce-79f583ad69b6)

**Comment by SherisseTJW** [comment]
I think the Prof. has answered your main question quite well, just some extra input from me as to custom exception handling since I also noticed this when I was doing the PR Review.

Personally, I prefer having multiple custom Exception classes (i.e., `InvalidCommandException`, `InvalidArgumentsException`) so that I can distinguish the different scenarios rather than having a simple catch-all `DukeException` class. This also allows you to define specific formats for the messages so that it is clearly standardised without having to copy paste the error message string multiple times.

Quick Example: 
```
public class InvalidCommandException extends Exception {
        public InvalidCommandException(String invalidCommand) {
            super("Invalid Command: " + invalidCommand + " received.\nOnly the following commands are accepted: list, add, bye";
        }
    }
```

**Comment by yisiox** [comment]
I'm not too sure about this, but I think the idea here is that we can let the classes doing the "low level" interactions handle the specific errors, and `Duke` doesn't need to be privy to specific errors. For example, `Storage` may encounter a `IOException` and is capable of handling it by terminating the attempt, but ultimately still rethrows the exception as a `DukeException` so that `Duke` is aware that something went wrong, but doesn't need to know the details. Also, `Duke` can log the error message rethrown by `Storage` for the user, which may be specific like `"failed to read file"` etc.

**Comment by JerryO3** [comment]
Personally, I ended up creating a custom exception class because there were some common exceptions thrown such as index out of bounds errors that may throw the same exception but from different parts of the application. By creating a custom exception class from which we can extend specific exceptions helped me to differentiate both, although I'm sure there may be a better way to do this.

**Comment by jeremiahlzz** [comment]
As Prof. has mentioned, exception handling is highly subjective and it is up you (or your team) to decide where to draw the line(s).

For me personally I consider `File Corrupted` and `File Not Found`, exceptions that should be handled in the `Storage` class. It relates to the storage data retrieval and as such, should be handled within and not by the external class utilizing it. This keeps a level of abstraction as external classes do not have to bother handling such trivial cases. Exceptions should be thrown (out of the class) only if the current class is unable to handle the error.

I agree with you in your example with the `DukeException`; if an appropriate exception is already available we should be using it instead of creating custom exceptions. I disagree with @JerryO3 's use (but it's not wrong to do so), as we can easily differentiate where the exception is thrown by simply following the stack-trace. Custom exception classes add a layer of complexity and if not named properly will cause confusion and decrease readability (like your example `DukeException`; what kind of error is it actually? I would not know without looking at code)

**Comment by timothysashimi** [comment]
I think using custom exceptions with custom error messages will help guide the user in using the software better

**Comment by justincred** [comment]
Thanks all, I think I agree that the exceptions such as file not found should be directly handled in storage class instead for abstraction purposes and also agree with @SherisseTJW with creating multiple exception classes for clarity and @jeremiahlzz in that adding a custom exception adds a layer of complexity if it does not do anything different and thank you prof @damithc  for the excellent answer! So i will be closing the thread now since there are several good answers already
