### ISSUE TITLE
SourceTree Pushing Error

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#231]
I keep getting this error message from SourceTree when I try to push. What does it mean? Please help
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/1493b417-29e1-4fd0-bded-7e4cc8b233aa)

**Comment by damithc** [comment]
@DominicFuMJ It means the tag `A-Packages` already exists in your fork but on a different commit than the commit your local `A-Packages` tag is attached to (you can confirm that by going to https://github.com/DominicFuMJ/ip/tags )
This can happen due to several reason e.g., you deleted the previous local copy of that tag and added it to a different commit
Git does not allow multiple tags to have the same name.

**Comment by DominicFuMJ** [comment]
Should I just create a different tag then? Like replace the current A-Packages tag with something else like A-Packages1?

**Comment by damithc** [comment]
> Should I just create a different tag then? Like replace the current A-Packages tag with something else like A-Packages1?

Yes, that's one way.
Alternatively, you can just delete the local A-Packages tag. As the tag is already in the fork, it will be detected by the dashboard anyway, irrespective of which commit it is in.

**Comment by DominicFuMJ** [comment]
Ok. I renamed the tag. Thank you
