### ISSUE TITLE
Scene Builder guides

### ISSUE THREAD

**Issue by TopKec** [nus-cs2103-AY2324S2/forum#237]
I've cleared the level-10 as required for the week, but checking out the page where everyone is sharing their GUIs, mine feels quite boring, to say the least.

I'd like to ask if anyone has some very useful guides, for stuff like how to expand the dialog box so you don't end up with stuff like the trailing ellipsis like mine has (Well, not just this, but in general making stuff look good and neater!):
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111767666/f9814d8b-e744-4902-95be-767e53495a68)

I'll definitely be refining this as an when I can though!

**Comment by yiwern5** [comment]
i replaced 'Label' with 'Text' so it doesnt end with ...
I also added a wrapping width so it wraps the text inside the dialog box :)

**Comment by damithc** [comment]
Thanks for the inputs @yiwern5 
@TopKec Is this issue resolved?

**Comment by TopKec** [comment]
Ah, apologies on not following up on this one.
While I can solve the issue as listed in the initial question, I still would like any Scene Bulder tutorials in general, but I can close it if this kind of further questioning isn't suitable for this forum!

**Comment by damithc** [comment]
@TopKec I guess there aren't any SceneBuilder guides around. We can keep this open for a while in case anyone found one and would like to share.

**Comment by flexibo** [comment]
Hi, I'm a senior from the previous batch!

I don't think I used a lot of SceneBuilder guides when I did my IP, but I do a lot of trial and error to get the result that I wanted. Most of the changes I made is within CSS or the Java code itself. Apologies if this is not what you are looking for, but this is how I made my own IP less "boring":

# General Visual Stuff
## Boring Stuff, but important to make it look neater
- Play around with padding (how much space you want to add into the element) and margin (how much space you want to add around the element)
  - This one need to trial and error with your SceneBuilder
  - Refer to https://www.youtube.com/watch?v=rBWA_t-KnKk for more information (since SceneBuilder uses CSS properties, and padding and margins are CSS properties) 
  - You can change the background color of the labels or elements to properly see what the margins and paddings do. 
  - Here is an example of padding usage in my DialogBox.fxml file:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40513197/2f1da8f8-52a5-4546-826d-3b417844efdf)
  - You can see the spacing around my label, that spacing is the result of the padding
  - **You can also add margin around the label especially between your profile pic and the label** 👀 👀 👀 👀 
- Restrict your height and width 
   - for me personally I didn't see a point in changing the width, and 
   - I am also lazy to figure out how to get the elements "stretch" along with the window
   - The minimum height is just to make sure that you can't minimize past the textbox and your scroll panel
```java
            stage.setMinHeight(230);
            stage.setMinWidth(417);
            stage.setMaxWidth(417);
```

## Slightly less boring stuff, to look good
- Curved and colored text boxes (what is [em](https://www.google.com/search?q=what+is+em+in+css&oq=what+is+em+in+css&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQLhhA0gEIMjQxNWowajGoAgCwAgA&sourceid=chrome&ie=UTF-8)?)
  - Note that the 4th parameter for rgb is the opacity (set to 0.5), which I like using it a lot especially for text boxes to make it look "atas"
```css
.label {
    -fx-font-size: 12;
    -fx-background-color: rgb(255, 243, 133,0.5);
    -fx-background-radius:1em;
}
```
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40513197/77684da9-7388-47d9-b55f-7c378e3b56de)

- You can set GIFs in images
  - For my profile pictures, I made use of GIFs because why not. It is the same as setting images.
  ```java
    private final Image cleoImage = new Image(Objects.requireNonNull(this.getClass()
            .getResourceAsStream("/images/dancing_cleo.gif")));
  ```
- You can set gradient colored backgrounds
  - https://edencoding.com/scene-background/ 

- Adjusting Scrollbar (I didn't like how the scrollbar looked)
  - You can refer to this for more info https://stackoverflow.com/questions/48048943/javafx-8-scroll-bar-css
```css
.scroll-bar {
    -fx-font-size: 5px;
}

.scroll-bar:vertical .thumb {
    -fx-background-color: rgb(255, 0, 0,0.3);
    -fx-background-radius: 10em;
}

.increment-button, .decrement-button {
    -fx-background-color: transparent;
    -fx-border-color: transparent;
}
```

# Audio Stuff (Bonus) 🎶 
- You can add audio to your application, so in my IP I actually added sound effects every time you send a message. Within my ``MainWindow.java``: 
 ```java
     private final AudioClip plonkSound = new AudioClip(Objects.requireNonNull(getClass()
            .getResource("/audio/click.mp3")).toExternalForm());
  
     @FXML
     private void handleUserInput() {
        plonkSound.play();
     }
 ```
- If you want you can also add a song command to [play a song](https://stackoverflow.com/questions/6045384/playing-mp3-and-wav-in-java) (must be free to use of course since you're pushing your code into GitHub)

# Other Resources
A lot of the design aspects come from CSS itself, so I highly recommend this link https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html 
And a lot of things can be found by searching ``JavaFX CSS`` into YouTube or Google or even CatGpt

This is my result (there is definitely still room for improvement, but I'm lazy to do more lol plus its super time consuming so I highly recc you to focus on other graded components first and only do this when you have the time), I hope this gives you some inspiration for your own IP :) 
![ezgif-2-26dd04516c](https://github.com/nus-cs2103-AY2324S2/forum/assets/40513197/de9b04fe-3a9a-4f9a-a732-23e547d7bfdd)

**Comment by kiwibang** [comment]
Hi, I too am a senior from a previous batch.
To add on to the wonderful writeup that @flexibo has very so kindly done, you can refer to the official [scene builder user guide](https://docs.oracle.com/javafx/scenebuilder/1/user_guide/jsbpub-user_guide.html)!

P.S. I personally strongly dislike doing UI touchups, so I apologise that I cannot be of much help. However, kudos for going above and beyond in your iP!

**Comment by SPWwj** [comment]
Hi, I too am a senior from a previous batch. 
To contribute to the above discussion, I find that this JavaFX Scene Builder tutorial is very structured and easy to understand. I hope this helps: [https://code.makery.ch/library/javafx-tutorial/part1/](https://code.makery.ch/library/javafx-tutorial/part1/)
