### ISSUE TITLE
Clarification on Week 5 PR merging

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#245]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/494d5fe5-db19-47c6-af15-2909f160b849)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/47e65b97-4217-4451-b0e9-1e2c7ee24324)

I am a bit confused about the steps here, I have created two PRs, one for Coding Quality and another for Assertions.

I merged Coding Quality PR and pulled my master and created a new commit (not the fast forward option). Step 3 says unmerged branches are no longer in sync, what are these unmerged branches? Is that not normal when we have updated our master? (I have yet to merge my Assertions PR).

'merge the master branch to each of them', usually we merge branch to master, now we switch to another branch and merge master to them? Are we referring to the branches we created up to this point from Week 2?

Also, why is there a push notification, when our master should be the same as upstream master? (Since we just pulled from upstream) (Im assuming this is because I didnt fast forward, is this not recommended) ?

Thanks

**Comment by damithc** [comment]
> I merged Coding Quality PR and pulled my master and created a new commit (not the fast forward option). 

When you pulled the upstream master, it should not have created a new commit. I guess not allowing the fast-forward caused the new commit.  Not your fault as we said not to allow fast-forwards. But this is a case where you should not force a merge commit as you are merging updates in the same branch (one local, one remote, but they are considered the same branch). In any case, the extra commit is not a big deal. In future, allow FF when when you pull the remote branch to the corresponding tracking branch in the local repo.


> Step 3 says unmerged branches are no longer in sync, what are these unmerged branches? 

In your case, `branch-A-Assertions`, which is not merged yet, and now not in sync because it doesn't have the latest commits of the master branch.

> Is that not normal when we have updated our master? (I have yet to merge my Assertions PR).

Yes, when the master branch moves forward, all branches created from it earlier fall behind (i.e., out of sync because they don't have some code the master branch now has)

> 'merge the master branch to each of them', usually we merge branch to master, now we switch to another branch and merge master to them? 

Yes, switch to , `branch-A-Assertions` and merge the `master` branch to it. That way, the latest code from the master branch will be added to that branch, making it in-sync with the master branch.


> Also, why is there a push notification, when our master should be the same as upstream master? (Since we just pulled from upstream) (Im assuming this is because I didnt fast forward, is this not recommended) ?

Because of the new merge commit you created in the master branch is not present in your fork. You can push the master branch to send it to the fork.

**Comment by UdhayaShan1** [comment]
Thank you so much, will take note of the (many) mistakes I made here

For the merging to unmerged branches, I may have done this wrongly by not merging to the unsync branches (branch-A-Assertion) in this case and merging through the PR directly. I resolved my merge conflicts through the online merge conflict tool on GitHub. I was wondering if this is considered a bad practice as compared to 

_**"Yes, switch to , branch-A-Assertions and merge the master branch to it. That way, the latest code from the master branch will be added to that branch, making it in-sync with the master branch."**_ first which I assume will allow me to resolve merge conflicts locally first instead of on the fork as I may have done wrongly.

**Comment by damithc** [comment]
> For the merging to unmerged branches, I may have done this wrongly by not merging to the unsync branches (branch-A-Assertion) in this case and merging through the PR directly. I resolved my merge conflicts through the online merge conflict tool on GitHub. I was wondering if this is considered a bad practice as compared to
> 
> _**"Yes, switch to , branch-A-Assertions and merge the master branch to it. That way, the latest code from the master branch will be added to that branch, making it in-sync with the master branch."**_ first which I assume will allow me to resolve merge conflicts locally first instead of on the fork as I may have done wrongly.

@UdhayaShan1 both are viable options, and it's good to learn both. The GitHub options is a new feature they added recently, and may be good enough for simple merge conflicts, while de-conflicting locally is safer (e.g., you can run tests to confirm the updated code is correct) and more standard (it's a standard Git feature).

**Comment by UdhayaShan1** [comment]
Thank you!

Will close this thread.
