### ISSUE TITLE
Help regarding OO design

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#247]
## The Aim
I'm aiming for code that is easily extensible in the sense that I can add new types of `Task` and `Handler`(a class encapsulating a the response to a command) easily. Therefore I want utility classes like `Storage` and `Parser` to only see `Task` and `Handler` instead of the specific subtypes like `TodoTask`. 

### What I Did
So far, I elected to use the Factory design pattern where there is a `TaskFactory` class that is responsible for creating a `Task` of the correct concrete subclass through a factory method, and similarly for `Handler`. This is an improvement over a previous design where `Task` itself handled the creation of subclasses, but this meant it "knew" its own subclasses, breaking abstraction. The intention is that adding a new type of task or command amounts to simply defining a new subclass of `Task` and/or new subclasses of `Handler` (for the associated commands), and modifying the factory methods' switch cases.

### The Problem
However, suppose the `Parser` has the following static methods:
```java
public static LocalDateTime parseDateTime(String dateTime) {
    return LocalDateTime.parse(dateTime, DATETIME_FORMAT);
}

public static Task parseStorageEntry(String entry) {
    String[] data = entry.split(",");
    return TaskFactory.of(data);
}
```
Somewhere down the line, `TaskFactory` will require `parseDateTime` to function, so I understand it as circularly dependent (Parser -> TaskFactory -> *Task -> Parser). So to prevent this I think I can either
1. Separate `Parser` more finely into `StorageParser`, `InputParser`, `DateTimeParser`, `AuxiliaryParser`, etc. This means `StorageParser` and `InputParser` are dependent on `Task` and `Handler` which are dependent on sibling classes `DataTimeParser` and `AuxiliaryParser`. But the main thing that doesn't feel right to me here is that none of these parser classes share fields or methods so do I just leave them as separate unrelated classes? I read of something called [marker interfaces](https://www.baeldung.com/java-marker-interfaces), - should I make them all implement an empty `Parser` interface to symbolize that they have a static `parse` method? (The methods are static thus the subclasses can't override some generic `parse`).
2. Again separate `Parser` into more specific subclasses, but make the `parse` methods generic and not static, meaning it can be overridden. So instead of the current approach where `Parser.parse*` can be invoked without instantiating a class, specific parsers need to be instantiated. Is this a better design over the previous?
3. Not have a `Parser`. Is this allowed?

I could also be going down the wrong direction entirely, if that is so do advise. Thanks in advance for any help.

Small edit: on the topic of enums I found [enum factory pattern](https://jvmaware.com/enum-as-factory/). On top of the options listed above there is another option of making the subclasses of `Task` handle date time by themselves, but this means that each subclass potentially has a different format.

**Comment by drustanyjt** [comment]
@yisiox actually it does feel like `parseDateTime` is a method that would only ever be used in your `TaskFactory`. Why not just move the method out from `parser` into `TaskFactory` instead? I'm guessing that you would have to do some kind of parsing of subcommands (like `/from` and `/to`) in the `TaskFactory`, so to me it seems like a natural extension would be to use `parseDateTime` there as well.

**Comment by yisiox** [comment]
@drustanyjt I wanted a unified and consistent format for printing also, so I wanted the subclasses of `Tasks` to call on some resource when processing `toString`. You're right that I missed that I can separate this out as this isn't "parsing" but rather formatting the output. Thank you for the input!

Currently I have committed to having a parsers package where `Parser` is the marker interface, then `InputParser`, `IntervalParser` (for BCD-extension) and `DateTimeParser` implement this interface. The storage parsing is a separate abstract `StorageParser` and concrete `TaskStorageParser`, and I made `Storage` use generics so it isn't specific to just handling `Task`. Also I replaced the factory classes in favour of enum factories, so types and commands have only fixed values, killing two birds with one stone. That said, I may have fallen into the premature optimisation trap not in the sense of speed but in the sense of extensibility, though hopefully it makes future increments easier.

**Comment by neyapraveen** [comment]
hi @yisiox , im from your senior batch, just dropping by the forum to see if I can help. To answer your question, let me start with point 3. I believe that not having a parser is not recommended because parsing is a significant part of the application in order to generate the corresponding output. Having a parser component helps to separate this responsibility, making the code more organised and maintainable. Thus you might want to avoid this if you want to promote code reusability. 

Approach 1: 
This approach can be beneficial for keeping the responsibilities of each class clear and maintaining single responsibility principle. While it is true that these classes may not share fields or methods initially, separating them allows for better organization and potential future extensibility. Using marker interfaces like Parser can be a good way to indicate common behaviour among these classes.
Pros:

-   Provides a clear indication that classes implementing these interfaces have a specific behaviour (e.g., static parse method).
-  Helps maintain consistency and clarity in the codebase.  
Cons:

- May introduce unnecessary complexity if the classes don't share any common fields or methods.
- Might lead to the proliferation of marker interfaces if you have many similar behaviours in your application.

Approach 2:
This approach allows for more flexibility and potential customization in parsing logic. By making parse methods non-static and generic, you enable subclasses to override and provide their own parsing implementations if needed. This approach might be suitable if different types of parsers require significantly different parsing logic.
Pros:

- Allows for more flexibility and extensibility by enabling subclasses to override parse methods.
- Promotes a more object-oriented approach, where each parser class encapsulates its own parsing logic.

Cons:

- Requires instantiation of specific parser classes, which may add overhead if parsers are created frequently.
- May lead to more verbose code compared to static methods.

Hope this helps you in making your decision

**Comment by kiwibang** [comment]
Hi @yisiox , am a senior from a previous batch! 

From what I can see, I believe we can avoid circular dependencies like this. First of all, I see that you have elected to use the `TaskFactory` class to produce `Tasks`, using the Factory design pattern. I am not sure of how when and how you use the parsers that you mentioned exactly, but if I were you, I would treat such parsers as a sort of tool to get the data in the right format. 

For example, if we were to take `parseDateTime`,  a parser that you implemented which will, if you allow me to hazard a guess, would be to take a `String`, and convert it into a Java `LocalDateTime` object containing the date & time information. This can be used in your `TaskFactory` method like a tool. Thus, I would suggest approach 1. 

I agree with @neyapraveen that approach 3 should be avoided. Additionally, approach 2 is possible but I personally would not opt for that due to these reasons:
- These parsers seem to be unrelated (other than the fact that they parse something)
- You have to instantiate an instance of a particular parser whenever you need it
- These parsers are general-purpose tools and would not make sense for them to be associated with particular instance of some parser superclass

Approach 1 to me is optimal for these reasons:
- The parsers are not related
- The parsers can be placed in a well-named package in your project, which can be imported like any Java standard library (e.g. Java's `Math` library), which reflects their characteristics as a nice tool that you can use in your application logic
    - This keeps the codebase neat & tidy even with multiple parsers implemented as multiple utility classes
- No need to create instances of parsers (assuming you did not use marker interfaces)

Hope this helps!

**Comment by yisiox** [comment]
@neyapraveen @kiwibang Thank you for the detailed comments. Ultimately I can agree with both of you that approach 1 is best in this case, and it's what I have gone with as well. It's the only place in the project so far that has this problem, so I think proliferation of marker interfaces should not be a problem. I can also keep the advantage of having them as static methods and having the package indicate that they have the parsing functionality.

Thanks again all for the input, will be closing this for now.
