### ISSUE TITLE
What if I don't use fxml?

### ISSUE THREAD

**Issue by sun-ruiheng** [nus-cs2103-AY2324S2/forum#264]
Hi all, since fxml does the same thing as classic JavaFX in a different manner, I'd prefer to stick to my original JavaFX as it's more intuitive for me. Would you foresee any difficulties in the future if I make this choice?
And is using fxml a requirement for our iP?
Thanks.

**Comment by gavingoh99** [comment]
Hey Ruiheng! This is just my own input, but I too had some initial apprehension when deciding on whether to adapt my JavaFX code to FXML (considering I had just done it the classic JavaFX way...). However, what I found very useful was that FXML uses .fxml files which can be read in SceneBuilder and handled like a CSS equivalent for Java! I highly recommend finding the time to attempt it so that you have a more accurate idea of which one you might prefer!

**Comment by damithc** [comment]
Good inputs @gavingoh99 
@sun-ruiheng using FXML is not a requirement for the iP. But it is used by AB3 already, which means you will encounter FXML in the tP.
