### ISSUE TITLE
Should assertion be caught like exceptions, exceptions vs assertions

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#275]
> If the runtime detects an assertion failure, it typically takes some drastic action such as terminating the execution with an error message. This is because an assertion failure indicates a possible bug and the sooner the execution stops, the safer it is.
https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/errorHandling.html#assertions  
  
For [`A-Assertions`](https://nus-cs2103-ay2324s2.github.io/website/schedule/week5/project.html#a-assertions)   
  
Can I assume that assertions will not be present in run time and there is no need to catch assertions?  
  
What is the difference with checking for edge cases with exceptions and handling them. Or it his a more fundamental issue   
e.g. We assume List.get should always return something so we can use an assert here, vs asserting that a user input is wrong which we use exceptions for instead  
  
As of now the GUI just hangs when an assert fails.  
  
Edit:
To add on, IntelliJ is saying that a of my assertions are 
```java
assert cmd != null : "Command is null, should never happen";
```
> Condition 'cmd != null' is always 'true'  
  
**if** my code is this "safe", is there a need to do an assertion?

**Comment by camille-readbean** [comment]
Oops to add on, I guess Assertions are just used to check that the __invariant__ is indeed invarying?  
  
https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html

**Comment by drustanyjt** [comment]
@camille-readbean your IDE probably did some preliminary parsing to determine that `cmd` is never `null`. You might make some change in the future which accidentally breaks this (and should hopefully be noticed during regression testing) so maybe it's not a bad idea to leave the assertion in.

**Comment by damithc** [comment]
> Oops to add on, I guess Assertions are just used to check that the **invariant** is indeed invarying?
> 
> https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html

@camille-readbean this is a good resource to follow.

**Comment by yisiox** [comment]
I think @drustanyjt made a good point that while the static analysis done by intellij confirms that that something will never occur, we might not notice when we change our code in the future and this is no longer the case, so I agree it might be worth keeping some of the assertions anyways.

>Why doesn't an AssertionError allow access to the object that generated it? Similarly, why not pass an arbitrary object from the assertion to the AssertionError constructor in place of a detail message? Access to these objects would encourage programmers to attempt to recover from assertion failures, which defeats the purpose of the facility.

>Why is AssertionError a subclass of Error rather than RuntimeException? This issue was controversial. The expert group discussed it at length, and came to the conclusion that Error was more appropriate to discourage programmers from attempting to recover from assertion failures.

I feel the resource is trying to convey that unlike error handling, which allows your program to gracefully recover from any error, asserts are not meant to be "recovered" from. They are more of a tool to help the programmer detect and correct bugs during testing and also tell readers information (like that of control flow invariants, assert false is a nice way to indicate default is never executed).

Using assertions to do input validation is also dangerous since it can be turned off, so if it is in any way important to the logic of the program it is fatal.

**Comment by camille-readbean** [comment]
Thanks for the help everyone @damithc @drustanyjt !!  
  
Can see the point of assertions in super critical software that needs safety guarantees. I added an assertion for a control flow invariant, e.g. a default branch in a switch statement that in theory should never be reached.
