### ISSUE TITLE
Query on CLI fast typing constraints

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#288]
We saw earlier that,

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/b5a4965e-b016-4c42-84a0-1d7f28f52a2d)

So, regarding this, if we implemented a sequential input system, for example system takes in user input by CLI by
1) name, system replies to type in address
2) address, system replies to take in income..
and so on.

Looking at this week's grading instructions for product design,
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/a91f8294-6afb-4406-aed5-261fa0862a0d)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/2851fb66-728c-48c8-8c2c-9d824a40d4b2)

It seems that this is actually a flaw and could weigh badly in grading. So I was wondering, if such sequential input is considered 'slow typing' as compared to a single line input where we have "add <name> <address> " and hence be considered a flaw?

Thanks

**Comment by tankh99** [comment]
Actually, I had a similar idea. I'm interested to hear the opinion on this too

**Comment by damithc** [comment]
This is a good aspect to discuss i.e., the UX merits of one-part-at-a-time approach vs the one-shot-command approach

In the meantime, note that this affects only the tP grading, not the iP grading (either approach is fine for the iP)

**Comment by camille-readbean** [comment]
I would suggest exploring an option where entering an incomplete command, or maybe the command only without the parameters ask for the arguments one by one. And also at the same time allow you to include all the arguments at the same time too

**Comment by tankh99** [comment]
> I would suggest exploring an option where entering an incomplete command, or maybe the command only without the parameters ask for the arguments one by one. And also at the same time allow you to include all the arguments at the same time too

This was exactly what I had in mind. In my opinion, this shouldn't be slower. A user can type it just as fast as the usual approach, if not even faster for 2 main reasons:
1. They don't have to stop and remember what were the input arguments
2. The method is less prone to errors. And if you fail, the error fails only for a specific section of the command and you don't have to retype everything

**Comment by UdhayaShan1** [comment]
@tankh99 Yes i agree, since its instant just see it as single line but with feedback but not sure if we are strict with this aspect for grading?

**Comment by damithc** [comment]
Suggestion: In addition to simply speculating/anticipating how the different approaches will affect the UX, you can also compare your experience of using UIs that follow one approach vs those that use the other. Preferably, ones you've personally used for real.
For example, Git CLI follows the one-shot command approach for the most part.

**Comment by damithc** [comment]
To add a few more points to ponder on this piecemeal vs one-shot approach to CLI. As usual, there are pros and cons on both. Before I mention some of the pros/cons you might not have thought of yet, here are two higher level observations that hints that the piecemeal approach is in the wrong direction.

1. If you look around, many CLI-heavy applications (e.g., Git, Linux, Gradle, etc.) use the one-shot approach for most commands. 
2. The piecemeal approach is like a GUI form, but we use text instead of graphical elements, show one field at a time, and the user can't go back to previous fields. In other words, 'like a GUI form, but worse'. which means it is probably not in line with our our goal is to create a _better_  (not worse) alternative to GUI-based input.

Now, we can dig deeper to see some of the factors not immeidiately apparent to us when we first try to compare the two.

1. For tasks that have many optional parameters, the piecemeal approach doesn't work well, as the user will not be able to specify only the needed parameters while entirely omitting the rest easily.
2. In the piecemeal approach, you have to stop and read what the console has printed out, multiple times, before a task can be completed. Alternatively, you have to remember the order in which the CLI will ask for parameters (and type without reading the prompt). In the one-shot approach you have to remember the prefixes but not necessarily the order of them, and they are not hard to remember for a seasoned user. Plus you can start thinking about the next parameter while you are still typing the current one (i.e., in one-shot you don't really need to _stop_ to think, but in piecemeal you really have to _stop_ to read)
3. Yes the piecemeal approach can notify the user immediately to re-input if the user inputs the wrong value for parameter but not all errors are detectable immediately.  Some errors can only be detected after all the values are in. Imagine the error turned out to be a typo in a previous parameter; the user might have to abort the whole command and start from the beginning. 
  In AB3, the previous command is automatically printed out if it wasn't successful. This means the user can easily correct the error wherever the error is, and hit enter again.
4. Another situation in which one-shot shines is when doing a few similar things with variations: just copy-paste the previous command (or use up arrow to access the command history), modify as needed, and hit enter.
5. A situation in which piecemeal approach shines is when doing rare tasks that require many parameters (e.g., one-off data imports/exports), or if subsequent parameters depend on previous parameters (e.g., if nationality is SG, the next parameter is NIC but  it is the passport number for all other nationalities). 
6. Any other factors I missed ... ?

In the tP:
* As recommended, pick an application domain that naturally lends itself to a CLI interface. If you chose a domain for which GUI-forms is a better input mechanism, you'll feel like the piecemeal approach is better for it too (because it is basically a text-based form).
* Still, the piecemeal approach has its value, and can be used in combination with the one-shot approach if you wish, to get the best of both worlds.

**Comment by UdhayaShan1** [comment]
Thanks Prof for your comments, discussed with my group and we decided in best interest of time and constraints, we will change to one-shot.

While we believe piecemeal could still be good in outside applications it might not necessarily be centric to CLI.

**Comment by jyztintan** [comment]
Hi Prof @damithc, With regard to our updated implementation idea, is it necessary for us to update the Value Proposition on our [Team List page](https://nus-cs2103-ay2324s2.github.io/website/admin/teamList.html):
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/98398940/ce45e789-ffb6-4ff0-9022-50771597ce5c)

If necessary, could you advice how could we go about to do this please. Thank you!

**Comment by damithc** [comment]
@jyztintan You can email me the revised value proposition.

**Comment by UdhayaShan1** [comment]
Hi Prof, sorry for the inconvenience, but due to the changes, our feature spec has also changed. Is it possible to resubmit (if we have to) without penalty?

Thank you

**Comment by damithc** [comment]
> Hi Prof, sorry for the inconvenience, but due to the changes, our feature spec has also changed. Is it possible to resubmit (if we have to) without penalty?

@UdhayaShan1 There is no need to resubmit. Just update it as necessary and use it as a reference when you implement v1.2

**Comment by UdhayaShan1** [comment]
Thank you!

Will close this thread
