### ISSUE TITLE
[tP] Question regarding Morphing

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#289]
Hi Prof @damithc, I would like to ask if we would to implement features with regards to managing meetings and its details associated to contacts is considered as morphing? Our team currently has two visions with regards to this as follows:

A contact can be associated/tagged with a datetime string that represents the meeting time

OR

A contact can be associated to zero or more meeting object that consists of details (e.g. datetime, location, etc.)

Will these two implementations be considered as morphing? Thank you!

Tagging my group members:
@Dethada, @KohGuanZeh, @Arixeyeion, @YuZizhen

**Comment by damithc** [comment]
@Javiery3889 Thanks for asking this in the forum (so that others facing similar situations can benefit from it).

As the product is required to be a primarily an address book app, other secondary elements (e.g., meetings in this case) are recommended to be light-weight, and added incrementally.

In your case, you should start with the first option, and evolve it further in the direction of the second option in later versions, but only if and when there is enough room for it in your tP workload. 

Reasoning: You should not choose the second option in advance because doing so will commit the team to a path that might inflict on you a higher workload than you initially anticipated. Only after you've managed to deliver the lighter version that you will know enough (based on your experience of building the lighter version)  to decide if you have enough resources (time, manpower) to evolve it to have stronger support for meetings.
