### ISSUE TITLE
Tags not shown on my IP

### ISSUE THREAD

**Issue by alvislowyh** [nus-cs2103-AY2324S2/forum#295]
HI guys idk why but some of my tags (I'm pretty sure i added them) are not shown. What to do?

**Comment by amanzainal** [comment]
It appears that the tags have been successfully updated on your [iP repository page](https://github.com/beefsausagee/ip/tags). If you're referring to tags added more recently, you might consider executing the command:

```
git push --tags
```

This command will push all tags that exist locally but are not yet on the remote repository, ensuring that all recent tags are properly synchronized. If the issue persists, feel free to provide additional details so that we can better address your concern! :)
