### ISSUE TITLE
Rebase for TP

### ISSUE THREAD

**Issue by g-tejas** [nus-cs2103-AY2324S2/forum#306]
Are we allowed to use rebase solely instead of merge?

**Comment by drustanyjt** [comment]
@g-tejas at the bottom of this week's [project page](https://nus-cs2103-ay2324s2.github.io/website/schedule/week6/project.html#4-get-familiar-with-the-code-base) they said don't rebase when merging PRs, and avoid it if you're syncing other local working branches with master.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/b610d7e9-c68a-4327-8b1c-9f45a68b399c)

They say the main reason is because it might mess up commit dates though, so I suppose if you're careful with the way you rebase, it might still be okay? My guess is there's some kind of auto grader that checks if you're constantly making commits through the weeks.

**Comment by damithc** [comment]
@g-tejas rebasing is discouraged in the iP/tP as it will interfere with our tracking of exactly when a commit was done. But we are not saying rebasing is bad in general. You are encouraged to learn it and use it outside of iP/tP.

**Comment by g-tejas** [comment]
Thank you both for the reply! We shall stick to merges
