### ISSUE TITLE
TP - Changing GUI for user input

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2103-AY2324S2/forum#308]
Hello!

At the moment, our team is working on feature specifications and mock-UI, and our team needs clarification on commend line input from the user side. Our group is aiming to make GUI for friendly for the users by allowing them to put input in form format (e.g. split single add ..... into --> Email: ______, Name: ________, Phone: ________ ....etc). Is this possible modification under the boundary of this tP project?

Thanks!!

**Comment by damithc** [comment]
@acekhoon at the risk of interfering with the discussion in https://github.com/nus-cs2103-AY2324S2/forum/issues/288, my advice is not to take this approach. There is a reason why other software such as Git use a one-short-command approach instead of piecemeal-command approach. The latter may be beginner-friendly but too clunky for seasoned users. It also doesn't do well when you have optional parameters. Imagine you decided to implement a piecemeal version of [this Git command](https://git-scm.com/docs/git-commit) and you see the problem already.  So, if at all, add it as an alternative for new users, not as a replacement for the one-shot-command approach. Also, delay this decision until you have been using AB3 for a while so that you have firsthand experience about how the input method feels to a user.
