### ISSUE TITLE
Overridden methods are resolved using dynamic binding, and therefore resolves to the implementation in the actual type of the object

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#31]
i know this sentence is true but dont understand what it really means. can someone give a real world example to explain

**Comment by yashma-sonara** [comment]
If an object is initially declared as type "Object" and instantiated as "Task" for example from iP. If you go to print the object, the toString() method from Task class is run, rather than the base toString() from Object class. This method resolution for overriden methods happens at runtime.

**Comment by jovantanyk** [comment]
There are two types of binding in java, static binding (early binding ) and dynamic binding (late binding). Overriding methods are resolved using dynamic while overloaded methods are resolved using static binding. The main difference between the two is the stage they take place in, static binding takes place during compile time while dynamic binding takes place during runtime. When you overload a method, the compiler is able to tell which method you're trying to call based on the method signature (name + parameter list). When you use method overriding, the compiler doesn't know which method you're trying to call since the method signature is the same in both subclass and superclass. Take this for example
` 
    public static class A {
        void print()
        {
            // Line 1
        }
    }

    public static class B extends A {
        @Override void print()
        {
          // Line 2
        }
    }

    public static void main(String[] args)
    {
        A a = new A();
        A b = new B();
        a.print()
        b.print()
`
During compile time objects aren't initialized yet, so when we do b.print() we have no idea which function to call, the one in the subclass or the one in the superclass. It is only after dynamic binding during runtime that we actually know which function to call. Hope this helps

**Comment by itstrueitstrueitsrealitsreal** [comment]
I was also pretty stumped by the jargon in the question at first, and I had to type out the classes to visualise what the sentence was trying to illustrate.

Suppose you have an is-a relationship between where the Task object is the parent class with the method `execute()`, with its child class having an implementation of `execute()` which overrides the parent's implementation, for example.

``` java
// Task is the type of object seen at compile time
public class Task {
    // ...
    // constructors and attributes omitted for brevity

    // This is the original implementation of execute as seen at compile time, and also the overridden method
    public void execute() {
        System.out.println("Executing task...")
    }
}

// Example is the "actual type of object" seen at run time
class Example extends Task {
    // ...
    // constructors and attributes omitted for brevity

    // This is the "implementation in the actual type of object", which is what is resolved to by dynamic binding.
    @Override
    public void execute() {
        System.out.println("Executing task...");
    }
}

public static void main(String[] args) {
    Task t = new Example();
    t.execute(); // compiler thinks it prints "Executing task", but actually resolves to execute() in the Example class
}
```

Hope I helped!

**Comment by E0735389** [comment]
CS2030S also has some concrete examples.

https://nus-cs2030s.github.io/2223-s2/14-polymorphism.html

**Comment by UdhayaShan1** [comment]
one thing to also note is which methods are accessible and which is not, this was not obvious for me at start

```ruby
class A {
    public void foo() {
        System.out.println("foo1");
    }
}

class B extends A {
    @Override
    public void foo() {
        System.out.println("foo2");
    }
    
    public void foo2() {
        System.out.println("ok");
    }
}



public class Main
{
	public static void main(String[] args) {
		A a = new B();
		a.foo();
		a.foo2(); //Does not run, as at compile time, a is created with type A and hence can only access A's methods and not B's despite new B().
	}
}
```

**Comment by damithc** [comment]
Thanks @yashma-sonara @jovantanyk @UdhayaShan1 @E0735389 @itstrueitstrueitsrealitsreal  pitching in with your explanations 💯
