### ISSUE TITLE
Cannot push Commits of A-CI

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#343]
Hi I have created the directory .github/workflows and added the gradle.yml file in that directory but I cannot push these commits.

Here is an image of the error.
<img width="1258" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/001d2524-2e54-452e-9748-6b6dcc76f4ca">

I googled this issue and they are telling me that I need to create a personal access token on GitHub, and include the workflow.

So what I did was:
1. Generate personal access token in GitHub.
2. Remember to include workflow when generating new token.
3.  Go to sourcetree -> settings -> accounts -> edit accounts -> update auth type to Personal access token -> paste the generated token from github.

Now I am Able to push the commits into my fork.

Just want to check if this will break anything regarding iP grading and whether there is another work around?

**Comment by Tanzhiheng26** [comment]
I followed the steps [here](https://docs.github.com/en/actions/learn-github-actions/using-starter-workflows) to set up CI using GitHub Actions. This allows you to set up CI on GitHub directly instead of creating the directory .github/workflows and adding the gradle.yml file locally.
After clicking on `New workflow`, click on `set up a workflow for yourself`, then you can paste the code from gradle.yml inside.

**Comment by jamz903** [comment]
Hi @ZhiWei1010 , I'm from your senior batch dropping by to see if I can provide some help.

When setting up CI on IntelliJ, this error will pop up as third-party tools like IDEs do not include permissions to modify Github Actions in the default scope when they create a token to connect to Github, thus the need to create a new token with the `workflow` scope. I don't think this will impact your iP grading, as it is giving your IDE permission to modify the Github Action files, but for an alternative approach you can follow what @Tanzhiheng26 suggested above! Hope this helps :)

**Comment by francisyzy** [comment]
Hi, senior from previous batch dropping by. Another workaround instead of using PAT would be using SSH Keys. This method would be more useful when using Git on the command line as you can forward your ssh keys to the remote server and use the same set of keys to authenticate with Github.

https://stackoverflow.com/questions/20644173/unable-to-get-ssh-keys-working-between-sourcetree-and-github#21189400

As for any issues with grading, if your code shows up fine on Github.com, it should be good. Just ensure the commit author name / email is the same as the ones as your other commits.

**Comment by seanfirefox** [comment]
Hi, senior from previous batch dropping by. I do the same as @francisyzy did as well, but I typically set it up by making a .gitconfig file on my home directory, with a sample below.

```
[user]
  name = Joe Doe
  email = joedoe@gmail.com
[core]
  editor = vim
  autocrlf = input
```

After which I setup the ssh keys on github. You can just use the command `ssh-keygen` on your computer, obtain the ssh key from `.ssh/id_rsa.pub` and paste the key into Github. This will setup both command line commits and committing from IDEs.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/35872524/1bea0edb-0de8-4a9a-be80-4eca9ed54c9e)

**Comment by garylow2001** [comment]
Hi @ZhiWei1010 ,  I'm a senior from the previous batch dropping by to see if I can provide some help.

In general after creating a new token to your workflow, you should be able to safely push your commits without breaking any iP grading :) . Here are some things you can check for to ensure the grading is successful:
1) Check that your previous commits and tags are unchanged
2) Check that the commit author (your username/email) is the same
3) Check your progress on the iP progress dashboard

**Comment by ZhiWei1010** [comment]
Thank you all for your sharing your alternate ways and solutions! I have figured things out and will proceed to close this issue!
