### ISSUE TITLE
[Need iOS] Difficulty With Cross-Platform Smoke Testing

### ISSUE THREAD

**Issue by larainezo** [nus-cs2103-AY2324S2/forum#370]
Hi, would appreciate if someone with a MAC can help to run my .jar file. I tried running through my friend's Macbook but got the following error:
```
Error: LinkageError occurred while loading main class duchess.Launcher
 java.lang.UnsupportedClassVersionError: duchess/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
``` 
This is a link to download the .jar file: https://drive.google.com/file/d/1llPgUUnjpKkiNKgYbXulU0WevHCJaY2V/view?usp=sharing

Thanks in advance!

**Comment by damithc** [comment]
@larainezo Tip: this is not an OS-specific problem. It's caused by a JDK version incompatibility. To start, you can try to find out which JDK versions map to class file versions 55 and 61 mentioned in the error message.

**Comment by larainezo** [comment]
Thanks prof @damithc.
I changed my SDK to version 11, but the same error is still showing.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/67939943/dd85229c-bb3c-4f07-9116-8340bca3a814)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/67939943/920fff93-b44e-445b-abac-0a7a57e8b12f)

**Comment by damithc** [comment]
@larainezo in the project root folder, run `java -version` command to ensure the correct JDK is being used, and run `./gradlew clean shadowJar` afterwards.

**Comment by larainezo** [comment]
@damithc Thanks prof! Seems to be correct for me
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/67939943/b5b19c22-3195-43d1-9fb3-503c7d3499c2)

**Comment by damithc** [comment]
> @damithc Thanks prof! Seems to be correct for me

@larainezo Did you try creating the jar from the same terminal as I suggested? Does that jar has the same problem as before?

**Comment by chiralcentre** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/bd5684fa-6ebf-48ba-9c38-b64aa02357b3)
Hi prof sorry to hijack this thread but I am facing a similar issue; I am unable to set the option to use Gradle from the "gradle-wrapper.properties file".
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/dd047aef-ed7b-439d-9438-02eba1ed6b55)
Even when I changed the Gradle JVM to Azul-11, when i run java --version on the terminal, it shows that the current Java runtime is Java 19. 
Can I check how can I resolve this issue?

Update: I downloaded JDK 11 from the following source [OpenLogicJDK](https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=406&field_operating_system_target_id=All&field_architecture_target_id=All&field_java_package_target_id=All) instead of the official Oracle source [OracleJDK](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html) because the Oracle website was down. Can I check if there will be any issues with this?

**Comment by damithc** [comment]
> Even when I changed the Gradle JVM to Azul-11, when i run java --version on the terminal, it shows that the current Java runtime is Java 19.
> Can I check how can I resolve this issue?

@chiralcentre This is a different issue. Intellij settings cannot control the terminal. You can post a different issue to seek how other Mac users got the terminal to follow the correct JDK version.

> Update: I downloaded JDK 11 from the following source [OpenLogicJDK](https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=406&field_operating_system_target_id=All&field_architecture_target_id=All&field_java_package_target_id=All) instead of the official Oracle source [OracleJDK](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html) because the Oracle website was down. Can I check if there will be any issues with this?

If you are using a Mac, you must use the Azul version we have prescribed. No other JDK should be used.

**Comment by chiralcentre** [comment]
Thank you Prof for the response; I am currently using a Windows PC. If that's the case does that mean there will be no issues?

**Comment by damithc** [comment]
> Thank you Prof for the response; I am currently using a Windows PC. If that's the case does that mean there will be no issues?

@chiralcentre In that case any JDK 11 should do. But you still need to set the terminal to point to JDK 11, by setting the `JAVA_HOME` system variable

**Comment by chiralcentre** [comment]
Thank you Prof for the response; I have updated the JAVA_HOME system environmental variable and released the JAR file accordingly.

**Comment by larainezo** [comment]
@damithc thanks Prof, I used the terminal in IntelliJ to build the JAR file. Is that okay?

**Comment by damithc** [comment]
> Prof, I used the terminal in IntelliJ to build the JAR file. Is that okay?

@larainezo Yes, the terminal inside IntelliJ is a normal terminal, just appearing inside IntelliJ for convenience.
