### ISSUE TITLE
Necessary to at least commit once each week for IP?

### ISSUE THREAD

**Issue by NeoHW** [nus-cs2103-AY2324S2/forum#410]
As per title, will IP marks be compromised if there are no commits in certain weeks, leading to a red item overdue marker in the IP progress dashboard as shown? 
![Screenshot 2024-02-25 at 3 49 56 AM](https://github.com/nus-cs2103-AY2324S2/forum/assets/94470439/2255a2b4-0127-4ff2-a6cd-22900d3a7b4b)
Especially for the final week, as some people might have finished up everything before the start of the final week

**Comment by damithc** [comment]
@NeoHW 4/5 weeks is good enough.

**Comment by E0735389** [comment]
This information can also be found in the course website: https://nus-cs2103-ay2324s2.github.io/website/admin/ip-grading.html#project-management-2-marks

Although note that it's also explained in another part of the course website:

https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html#ip

>  We discourage you from doing project tasks allocated to future weeks. Reasons: In order to help you gain fluency (and also to better simulate real projects), we want the project work to be spaced and span a longer period, rather than to be done as a short burst.
>
> Reminder: as per iP grading criteria, some increments need to to be done in each week for you to get full marks. That is, clumping all the iP work into a short burst of work will not earn you full marks.

Since week 6 has a nonzero amount of work (make course website), unless the student intentionally do things of future weeks, it should not be possible to finish everything before the start of week 6. (Of course this can be loop-around-ed by leave the last commit uncommitted but that's not the point...)

Still, it's good that you find no trouble with finishing the project quickly.

**Comment by NeoHW** [comment]
thank you all for the input
