### ISSUE TITLE
Asking about necessary use cases

### ISSUE THREAD

**Issue by KohGuanZeh** [nus-cs2103-AY2324S2/forum#416]
Hi, I would like to ask about representative use cases required for the DG for v1.1 on behalf of my team @AY2324S2-CS2103-F15-1.

> Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)

> Important use cases missing (a use case is important if it involves a user interaction that is worthy of documenting e.g., it has multiple extensions -- this is not the same as the feature being important)

1. To clarify, suppose the add contact feature does not have multiple extensions. Although it is a core feature, it is alright to exclude it from the use case in our DG?

2. What is considered having multiple extensions? For instance, `delete` in the current DG has 2 extensions. Do we use that as the baseline where all user cases that have more than or equal to 2 extensions should be included?

3. What if we have multiple use cases that have very similar paths. For instance, if many of our index based commands are similar to `delete`, will the `delete` use case alone be sufficient? Or suppose we have a more complex index based command such as `edit` which also includes extensions with invalid fields (where values do not comply for instance). Can we include the `edit` command only? Or are we recommended to still include both `delete` and `edit`?

Thank you!

**Comment by damithc** [comment]
> * To clarify, suppose the add contact feature does not have multiple extensions. Although it is a core feature, it is alright to exclude it from the use case in our DG?

@KohGuanZeh Yes

> * What is considered having multiple extensions? For instance, `delete` in the current DG has 2 extensions. Do we use that as the baseline where all user cases that have more than or equal to 2 extensions should be included?

"Is this feature/user-story worth documenting as a use case?" is a question you'll need to answer yourself, for each case. It is not tied to a specific number of extensions. For examples, you can decide to not document a use case with five extensions because there is another very similar use case is documented already. 

BTW, while the number of extensions is a factor, the primary factor is '... that need multiple _steps_ to complete'.  So, a user story might still be worth documenting even if it doesn't have _any_ extensions. 

> * What if we have multiple use cases that have very similar paths. For instance, if many of our index based commands are similar to `delete`, will the `delete` use case alone be sufficient? Or suppose we have a more complex index based command such as `edit` which also includes extensions with invalid fields (where values do not comply for instance). Can we include the `edit` command only? Or are we recommended to still include both `delete` and `edit`?

There is no value in duplicating the same thing. So, when two things are similar but not exactly the same, it may be better to document one and state the other is similar, and also explain how the second one differs. e.g., _Similar to UC2 (add user) except in the step 2 ..._

**Comment by KohGuanZeh** [comment]
@damithc Understood, thanks prof!
