### ISSUE TITLE
Jar File

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#424]
im smoke testing my jar file and nothihng happens if i double click the jar file. but if i go into terminal and run 
java -jar Gops.java it works

is this the expected behaviour?

**Comment by damithc** [comment]
@bgopi23 From a course requirements POV, it's good enough if the jar can be launched using the terminal.

Which OS are you using BTW?

**Comment by baskargopinath** [comment]
@damithc im using macOS sonoma

**Comment by c-wenlong** [comment]
mine is sonoma as well but it works when i double click, what does it say when u click into it?

**Comment by guanquann** [comment]
I'm on windows, and I need to add the `-jar` command for the jar file to be launched.

**Comment by baskargopinath** [comment]
i can double click other peoples jar file and it opens the chatbot without needing cli 

but for mine it only works when using cli

@c-wenlong doesnt say anything

**Comment by jocelyn-soh** [comment]
I faced a similar issue before but I'm using windows so not sure if my solution will be helpful. The problem that I faced was I used the wrong jar file association (I was using jre instead of jdk). 

In terminal, I checked for the current jar file association using `ftype | find "jarfile"`. My jar file association was: `jarfile="C:\Program Files\Java\jre-1.8\bin\javaw.exe" -jar "%1" %*`. 

Using the Registry Editor application, I clicked into the following path: `Computer\HKEY_CLASSES_ROOT\jarfile\shell\open\command`. 
Then, I updated the jar file association to: `"C:\Program Files\Java\jdk-17.0.5\bin\javaw.exe" -jar "%1" %*`.  Note that your version of jdk and jre may differ slightly so do edit the paths accordingly. 

You may also want to read through these 2 stack overflow discussions ([discussion 1](https://stackoverflow.com/questions/5827164/why-does-my-jar-file-execute-at-cmd-but-not-on-double-click?rq=3), [discussion 2](https://stackoverflow.com/questions/9259389/jar-file-doesnt-open-upon-double-click)) that I referred to for other solutions.

**Comment by baskargopinath** [comment]
@jocelyn-soh okay thx

**Comment by damithc** [comment]
> I faced a similar issue before but I'm using windows so not sure if my solution will be helpful. The problem that I faced was I used the wrong jar file association (I was using jre instead of jdk).
> 
> In terminal, I checked for the current jar file association using `ftype | find "jarfile"`. My jar file association was: `jarfile="C:\Program Files\Java\jre-1.8\bin\javaw.exe" -jar "%1" %*`.
> 
> Using the Registry Editor application, I clicked into the following path: `Computer\HKEY_CLASSES_ROOT\jarfile\shell\open\command`. Then, I updated the jar file association to: `"C:\Program Files\Java\jdk-17.0.5\bin\javaw.exe" -jar "%1" %*`. Note that your version of jdk and jre may differ slightly so do edit the paths accordingly.
> 
> You may also want to read through these 2 stack overflow discussions ([discussion 1](https://stackoverflow.com/questions/5827164/why-does-my-jar-file-execute-at-cmd-but-not-on-double-click?rq=3), [discussion 2](https://stackoverflow.com/questions/9259389/jar-file-doesnt-open-upon-double-click)) that I referred to for other solutions.

Thanks for sharing this useful info, @jocelyn-soh
