### ISSUE TITLE
Alternate git workflow query

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#425]
Based on this 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/e2d5e673-d163-4111-a6d5-c5fe37c94e56)

Suppose, I have created a new PR from my forked repo to team repo. We learnt that, after this PR is merged in team repo, we should directly pull to our local repo then push from there to our forks.

What if,
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/efc895d9-12fc-433f-81ca-aad2f2ff55e0)

We used the GitHub Web UI to sync our fork first with the upstream team repo. Then simply pull from there to our local repo. 

Is there any pitfalls or are they just the same?

Thanks

**Comment by damithc** [comment]
It is best to start using Git CLI at this point, rather than rely on GitHub UI. The chances of using GitHub in your future internships is low but Git is almost guaranteed.

So, just do a `git pull upstream master` followed by `git push origin master`. It's in fact faster than the GitHub UI route, which still requires a Git pull. 
To make it one step, put the two commands in in a shell script. 
Or define a command alias in your git bash e.g., `alias sy='git pull upstream master && git push origin master'` after which you just need to type `sy` in your git bash and hit enter -- voila! both steps are done in one shot.

**Comment by UdhayaShan1** [comment]
Thank you!
