### ISSUE TITLE
[IP] Wrong tag names

### ISSUE THREAD

**Issue by alvislowyh** [nus-cs2103-AY2324S2/forum#430]
Hey guys for some of my tags i put the wrong name. So to clear the dashboard, i just push empty tags with the correct name. Should i delete the old ones?

And could someone tell me if i release my Jar properly? the dashboard did not update. As well as my Git-standard component is still red.

<img width="774" alt="Screenshot 2024-02-26 at 11 19 20 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/157791089/0af4056c-67d6-44c0-94e3-526cab0cab0c">

**Comment by Darkarche3** [comment]
I am not sure but I don't think you need to delete the old tags. The system should look for the right ones.

For the jar part, the page updates daily. If it has not turned green, it might simply mean you have to wait for the next time the system checks your work. 

you git standard component is red because your commit subject messages are not correct. This tag tracks your last 5 git commits. As long as the standard is followed it will turn green.  It should become green once you do them correctly.

**Comment by Jerome-j** [comment]
Hi your git commit messages are wrong form

It should be present tense: Implement XXXX

for your Jar i think you did everything correctly, you need to wait for the dashboard to refresh cos it was last updated 2218 yesterday

**Comment by damithc** [comment]
Yup, what @Jerome-j  and @Darkarche3  said :-)
