### ISSUE TITLE
Smoke Test Help on Linux and Windows

### ISSUE THREAD

**Issue by AdityaB4** [nus-cs2103-AY2324S2/forum#442]
Hello! Please help me smoke test my release on Linux and Windows. My previous release failed with the error below:
```
Error: JavaFX runtime components are missing, and are required to run this application
```

You can find the release [here](https://github.com/AdityaB4/ip/releases/tag/v0.3), and the docs / user guide [here](https://adityab4.github.io/ip/).

Thank you!

**Comment by blaukc** [comment]
it works for me (windows 10)!

**Comment by dedsecrattle** [comment]
Works for Windows and Linux (Kali Linux)

**Comment by cbj252** [comment]
Hello, senior from a previous batch here.
Your application runs for Ubuntu 22.04.3 via Oracle VirtualBox, but I struggled to get your program to add a deadline. I copied the example from Level-8 from https://nus-cs2103-ay2324s2.github.io/website/admin/ip-w3.html and the system does not recognize it.
I also tried similar combinations, thinking it might be restrictive date and time parsing, but was still unable to do so. I can use the todo, mark and delete commands. You may wish to state the format requirements of your commands in your application or GitHub page.

Please ignore this suggestion if you believe your coursemates would be able to execute commands without issue with the information given to them.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/5f851f50-1172-4e72-9d20-54188c9303e6)

**Comment by lhy-hoyin** [comment]
Hi @AdityaB4, I'm a senior from a previous patch and is helping you to smoke test using Linux (Ubuntu 22.04.4).
For some context:, running `java --version`
```shell
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
```

Running `java -jar Whisper.jar` gives:
```shell
Feb 29, 2024 2:08:18 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @36d6f423'
Error in glXCreateNewContext, remote GLX is likely disabled
```

---

Smoke of testing was hard because there was't any documentation of how to use the application. Usually, a "help" command exists to let the user know what are the available commands.

So far, I have managed to (guess and) test the following commands
- list
- todo
- find
- mark
- unmark
- delete
- bye

As mentioned by @cbj252, the expected format for the date/time is virtually unguess-able. (I even peeked at the source code, but I still can't figure it out TuT)

**Comment by AdityaB4** [comment]
@blaukc @dedsecrattle Thanks so much for helping out! Would it be possible for you to share the Java version that you used as well?

**Comment by AdityaB4** [comment]
@cbj252 @lhy-hoyin Thank you for helping out and even trying to reverse engineer documentation. I completely forgot that seniors were also helping out in the forums 😅.

I've edited my issue description to now include a [link to my docs as well](https://adityab4.github.io/ip/).

Thanks again for the help, and apologies for the incomplete information!

**Comment by AdityaB4** [comment]
@lhy-hoyin Just to double check: does the jar file execute at all on your distribution of linux and java version?

**Comment by lhy-hoyin** [comment]
@AdityaB4 yup, I was able to run the jar with my Ubuntu and java version.

**Comment by francisyzy** [comment]
Hello, senior from a previous batch here, testing on Kali

<img width="764" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/83bf1ad1-ab55-43cb-ae86-1d98de9a8a7c">

I think the specific command error handling should not throw `I do not know what it means` when marking a task that doesn't exist. But otherwise it runs fine on Linux.

**Comment by AdityaB4** [comment]
Thank you @francisyzy for helping with the test!
