### ISSUE TITLE
Need help for Smoke Test (LinkageError)

### ISSUE THREAD

**Issue by YuZizhen** [nus-cs2103-AY2324S2/forum#455]
Hii, my IP is [here](https://github.com/YuZizhen/ip). My program seems to work fine on my computer but I received an auto generated error message from the feedback. It looks like:

Error: LinkageError occurred while loading main class Launcher java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Thankss!!

**Comment by Darkarche3** [comment]
Hi, I ran your jar file and I also got the same error as you. Try recreating a new Jar file and testing it again. If you get the same error, check that you are using the correct Java version.

**Comment by dabzpengu** [comment]
This means that your jar file was compiled with a newer version of Java. Check the SDK that you are using in your IDE, if your IDE is IntelliJ, go to Files > Project Structure. Make sure the SDK is Java 11. If not, download it then re-run shadowJar from gradle. Hope it works!

**Comment by YuZizhen** [comment]
Thanks! I checked my JDK is 11. I re-run the shadowJar and update the Jar file with the newest version. Can yall help to check whether it works? Thanks!! Because both the old one and new one I can run on my laptop...

**Comment by damithc** [comment]
@YuZizhen use a  regular terminal to run `java -version` (to confirm Java 11 is being used), followed by `./gradlew clean shadowJar`.
If you run Gradle tasks via Intellij, make sure you have _both_ settings mentioned in scenario 1, step 3 in [here](https://se-education.org/guides/tutorials/gradle.html#:~:text=correct%20Java%20version) are correct.

**Comment by YuZizhen** [comment]
Thanks prof! However my java version is 17.. But all the steps about settings in IntelliJ are correct. I re-uploaded the compiled file.

**Comment by baskargopinath** [comment]
@YuZizhen 
i get this error on mac
"Java launch application failed"

**Comment by YuZizhen** [comment]
@bgopi23 Hmm do you have any idea why it failed... it works fine on my side so I have no clue why the linkage error or your failed run happens :(

**Comment by damithc** [comment]
> Thanks prof! However my java version is 17

@YuZizhen You need to change this to 11 by setting JAVA_HOME system variable to point to JDK 11.

**Comment by dabzpengu** [comment]
> Thanks prof! However my java version is 17.. But all the steps about settings in IntelliJ are correct. I re-uploaded the compiled file.

hi, your terminal and IDE can be using different java versions. IDE is an integrated environment and is separate from your terminal, when you do `java -version` it checks your own environment variables which is **separate** from IntelliJ's configuration. So, while you may have ensured that IntelliJ and Gradle is using java 11, if your terminal is detecting java 17, it will not be able to run files compiled using java 11

> @bgopi23 Hmm do you have any idea why it failed... it works fine on my side so I have no clue why the linkage error or your failed run happens :(

when you say "works fine", did you use your terminal to run or you run Launcher.java directly on intelliJ? The latter works because as mentioned earlier, it is an integrated environment. 
If you can run it on your terminal, but other users could not run in on theirs, then it is very likely that you did shadowJar with a different java version

here's a few things to check:
1) run `java -version` in **your terminal**, make sure its java 11
2) check intelliJ's SDK again just to be sure it is also java 11
3) check your fxml files again just in case
4) go to Files > Settings, look for Gradle and check "Gradle JVM", make sure it uses java 11 which should match the project's SDK

hope this helps!

**Comment by YuZizhen** [comment]
@damithc @dabzpengu I managed to change the environment! I have uploaded the newest version compiled with java 11. Thanks!!! (but still need some help for the smoke test to see whether the newest one works!! It works on my computer :)

**Comment by zhenghuil** [comment]
@YuZizhen Downloaded and ran new jar file on my windows laptop in the terminal and it seems to be running well.

**Comment by ashleyclx** [comment]
Yup can confirm it is working on windows. 👍

**Comment by YuZizhen** [comment]
@zhenghuil @ashleyclx Thank yall very much!!!
