### ISSUE TITLE
Requesting help for smoke test

### ISSUE THREAD

**Issue by reetmitra** [nus-cs2103-AY2324S2/forum#467]
Recently I faced some issues with my smoke test, it was working on mac linux and windows but I received this today: 

On Windows, using Java 11, for the duke.jar uploaded on 03-03-2024 (MM-DD-YYYY) at 22:38:38:
Graphics Device initialization failed for : d3d, sw Error initializing QuantumRenderer: no suitable pipeline found java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280) at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94) at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124) ... 1 more Exception in thread "main" java.lang.RuntimeException: No toolkit found at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at java.base/java.lang.Thread.run(Thread.java:834)
On Linux, using Java 11, for the duke.jar uploaded on 03-03-2024 (MM-DD-YYYY) at 22:38:38:
Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280) at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94) at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124) ... 1 more Exception in thread "main" java.lang.RuntimeException: No toolkit found at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at java.base/java.lang.Thread.run(Thread.java:829)

Could someone help me out please.

Latest release : https://github.com/reetmitra/ip/releases/tag/A-NewRelease

**Comment by damithc** [comment]
@reetmitra A similar case that got resolved previously https://github.com/nus-cs2103-AY2324S2/forum/issues/451

> Latest release : https://github.com/reetmitra/ip/releases/tag/A-NewRelease

This one won't do for sure, The file size is too small for it to be correct (91.9 KB).

**Comment by reetmitra** [comment]
> @reetmitra A similar case that got resolved previously #451
> 
> > Latest release : https://github.com/reetmitra/ip/releases/tag/A-NewRelease
> 
> This one won't do for sure, The file size is too small for it to be correct (91.9 KB).

@damithc I'm getting this now : ./gradlew clean shadowJar                                                                                                                                             ─╯

> Configure project :
Project : => no module-info.java found

BUILD SUCCESSFUL in 597ms
4 actionable tasks: 4 executed

**Comment by damithc** [comment]
@reetmitra does ` ./gradlew clean shadowJar` create a duke.jar file? What's the size?

**Comment by reetmitra** [comment]
@damithc it does, size is about 8MB

**Comment by damithc** [comment]
You can upload that one and ask others to smoke-test it, but first, run the `java -version` command in the same terminal you ran the gradle command, to verify you are using the correct Java version to create the JDK. If you are on a Mac, ensure it is the correct Azul JDK that we have prescribed.

**Comment by reetmitra** [comment]
openjdk version "11.0.22" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu11.70+15-CA (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.70+15-CA (build 11.0.22+7-LTS, mixed mode)

This is my output (for Mac). 

Latest release : https://github.com/reetmitra/ip/releases/tag/A-Release

**Comment by cbj252** [comment]
Hello, senior from a previous batch here, testing on Ubuntu accessed via VirtualBox, Java version openjdk  "11.0.22" 2024-01-16.

The program runs, but I encountered some issues:

- The program doesn't save data into any file. i.e. If you put in three tasks, close the application (via bye or otherwise), and reopen it, there will be zero tasks in the program.
- The deadline command runs into an error, as shown in the screenshots below. I took the example command from your user guide - and tried a few similar alternatives, but I couldn't get it to work.
-  While I could make the event command work with:
`event Project meeting /at Monday 10am from 2024-02-25 1600 to 2024-02-25 1601`, the example command from your user guide, `event Project meeting /at Monday 10am` fails because it doesn't specify the time.
- You may wish to make your user guide more prominent: there's both your user guide at docs/README.md and the original README.md from the duke project template. The duke project template is easy to see as it's on the github home page, yours is not and some people may miss it. Consider editing the duke project template readme to include your user guide if allowed to by the module requirements.

Other commands, like find, mark, unmark, todo, delete and bye work as expected.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/ce6ae27a-db50-4348-bd67-b42b648610bb)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/7f367103-0bbf-4480-81f3-667a88855e55)

**Comment by reetmitra** [comment]
@cbj252 thank you for the feedback, I will work on it.
