### ISSUE TITLE
Cannot find addressbook.json

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#472]
Could someone tell me where the addressbook.json is located that needs to be deleted according to the tutorial. I am not able to find it under my data directory

**Comment by Jerome-j** [comment]
Try to create one new contact using the `add ...` command. I had a similar issue as you,

**Comment by radeon2525** [comment]
But how do I use the add command without running the program, since in the instructions they tell us not to run the program without deleting the file first

**Comment by Jerome-j** [comment]
Try running the program anyways?

**Comment by radeon2525** [comment]
Okay, so I successfully have generated that file, do I need to now delete it everytime I implement an add command

**Comment by damithc** [comment]
@radeon2525 
1. Delete that file if it exists, otherwise no need to delete it. 
2. Furthermore, you need to delete it only when you change the code in a way that makes the previous format of the data file incorrect i.e., if you change the properties of Person objects. Reason: If AB3 sees that the data file is not in the expected format (e.g., missing an expected data field) it will discard the current file and start with an empty address book). But if the file is not there at all, AB3 will create the file and populate it with the sample data, in the new format. Either way, it is not a big deal because you only lose the sample data. You can always add more data using the add command.

**Comment by radeon2525** [comment]
Okay understood prof, thank you
