### ISSUE TITLE
Using Sourcetree for source control

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#484]
I remember the course website saying that it is recommended to use the terminal instead of Sourcetree for source control.

Is it okay to pull via Sourcetree like the following instead of "git pull (upstream) master"?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/a00f2cda-6403-4001-a05d-b2b8b5bb2226)

I read that pulling via Sourcetree creates an automatic merge commit. I'm not sure if this is an ideal case.

**Comment by damithc** [comment]
@jeong-jaeho It's fine to use either but pull is a very common action that you should know how to do in CLI as well.

**Comment by jeong-jaeho** [comment]
@damithc Prof, I was wondering if it is okay if I pull from the main tp remote repo by creating a new commit even if fast-forward is possible as the following using SourceTree:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/6b8d2416-33fa-470a-94ec-f4409d095378)

I remember that we were told to create a new commit and not do fast-forward for merging, but looking back, not sure if we are recommended to do this for pulling. I remember that using just the CLI pulling method using 'git pull (remote repo) master' doesn't create a new commit and shows as a single connected branch between team repo and my own forked repo. On the contrary, creating a new commit even if fast-forward using SourceTree looks as the following after I've pulled the updates on main repo and pushed the changes to my own forked repo:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/80ed703a-b7f4-4e4d-b979-257995a6f06a)

**Comment by damithc** [comment]
@jeong-jaeho either way is fine, but if you follow the forking workflow correctly, your master local branch will only fall behind but should not _diverge_ from the team repo master branch, which means there should not be a need to create a merge commit or do a fast forward when you pull. So, these two options will not have any effect. This is because, when following the forking workflow, you always do your changes in a separate branch, and you get _all_ master branch updates from the team repo. Hence, your local master branch never diverges from the team repo master branch.
If a pull ended up creating a merge commit or a fast forward, you must have deviated from the forking workflow earlier.

The remedy: Follow the forking workflow correctly from now on. It is common for students to make mistakes with the forking workflow at the start. There is no penalty if you learn and follow the workflow correct in due course.

**Comment by jeong-jaeho** [comment]
@damithc Prof, I didn't revert from the wrong forking flow as you suggested, and I just pulled the newly merged PR my team mate made using 'git pull (remote team repo) master' in CLI instead of using SourceTree. 
![스크린샷 2024-03-14 212652](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/a93eb061-1895-42fc-b3a3-bb06301ee016)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/b3071eb4-953e-457f-8a98-04c89dff8663)


However, it seems that it's not following the normal forking flow since origin/master and tp/master are not in a contiguous branch. I'm assuming the previous wrong forking flow is causing a new merge to be made each time..? 
I didn't push the pulled changes into origin/master yet just in case. 
Or am I wrong, and it is indeed going back to proper forking flow when I push the pulled changes?

Is it okay to delete my current tp forked repo from my github repository, fork the team tp repo into my own repo again, and start again with the correct forking flow? Would all my previous work be still recognized by the system when tracking?

**Comment by damithc** [comment]
> Is it okay to delete my current tp forked repo from my github repository, fork the team tp repo into my own repo again, and start again with the correct forking flow? Would all my previous work be still recognized by the system when tracking?

@jeong-jaeho Yes, this should be fine i.e, delete your fork, fork again, clone it to a new location in your computer, and start doing work in that clone.
