### ISSUE TITLE
Git branch naming conventions?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#487]
I notice that the names of the branches for the iP does not satisfy the guidelines in https://se-education.org/guides/conventions/git.html#branch-names : some characters are in uppercase e.g. `branch-Level-9` , and that the word `branch` seems to be unneeded (we should not be naming every branch starting with `branch-`, right?)

Another example is `branch-A-CI` for the `A-CI` tag. Can I confirm that the normal kebab-case guideline is to write everything in lowercase, including the abbreviations? (the example in https://se-education.org/guides/conventions/git.html puts the `ui` lowercase)

Then why are they implemented that way for the iP? (One reason I can think of is for the automated grading script, but why not just name the branch `level-9` instead?

**Comment by damithc** [comment]
@E0735389 branch naming convention is not [enforced](https://nus-cs2103-ay2324s2.github.io/website/admin/standardsAndConventions.html) in this course but you are free to follow it you wish.

In the iP, the branch name decisions were based on level names. For example, adding `branch-` in front the level name (to differentiate it from the Git tag), and using the same case as level name (for convenience) rather than use different cases for different things.
