### ISSUE TITLE
Consider using a youtube timestamp for W8.5e

### ISSUE THREAD

**Issue by miffi** [nus-cs2103-AY2324S2/forum#493]
This is not a bug per se, but that's the closest tag there is.

W8.5e has this highlighted part telling us to watch 4 minutes and 50 seconds in. I was thinking it'd be better if the youtube url was timestamped itself like so: https://www.youtube.com/watch?v=QDFI19lj4OM&t=290s

Of course, this has the possibility of disorienting users who expect to watch the whole video so a disclaimer might still be necessary.

**Comment by damithc** [comment]
Thanks for your suggestion @miffi 
The reason why the timestamp was not not used in the way you suggested is because the [MarkBind syntax that was used to embed the Youtube video](https://markbind.org/userGuide/formattingContents.html#embedding-youtube-videos) doesn't support encoding times into the URL.

**Comment by miffi** [comment]
That makes sense :+1: . Then I guess this is not really an issue for the book. Closing.
