### ISSUE TITLE
Unable to run runtest.bat

### ISSUE THREAD

**Issue by Lin-Shuang-Shuang** [nus-cs2103-AY2324S2/forum#51]
When I try to run it, an error shows up:
`'javac' is not recognized as an internal or external command, operable program or batch file.`
May I know how to resolve this.

**Comment by vnnamng** [comment]
The problem seems to be that you have not set your JAVA_PATH (basically point the command javac towards a .exe file in your java installation folder).
Here is a tutorial that I follow that work for my friend computer: [Tutorial](https://www.geeksforgeeks.org/how-to-set-java-path-in-windows-and-linux/).
