### ISSUE TITLE
Individual tp progress 

### ISSUE THREAD

**Issue by HongRay** [nus-cs2103-AY2324S2/forum#511]
Do we have to contribute commits to the master branch of the team repo weekly? The duration for v1.2 is 2 weeks but the individual tp progress tracker says that we need to commit to the master branch of the team repo weekly. However, I am only committing to my fork and did not submit a pull request. Do you advise submitting an incomplete (PR)?

**Comment by damithc** [comment]
@HongRay The grading scripts go by the timestamp of the commit, irrespective of when the commits were merged to the team repo. 
Suppose you created some commits in week 8 but did not create a PR (because the feature is not complete yet). And in week 9, you added some more commits, and created a PR, which was merged. At that point, the grading scripts will see your commits in the team repo, and will recognize that you committed in week 8 as well as week 9, turning both weeks to green. But until the PR is merged, week 8 will stay red (which is fine).

**Comment by HongRay** [comment]
> @HongRay The grading scripts go by the timestamp of the commit, irrespective of when the commits were merged to the team repo. 
> Suppose you created some commits in week 8 but did not create a PR (because the feature is not complete yet). And in week 9, you added some more commits, and created a PR, which was merged. At that point, the grading scripts will see your commits in the team repo, and will recognize that you committed in week 8 as well as week 9, turning both weeks to green. But until the PR is merged, week 8 will stay red (which is fine).

Thank you Prof!
