### ISSUE TITLE
Question on tP code quality

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#512]
Can I ask what is the rationale for some of the code quality decisions in the tP sample code?
1. Why does each command have their own class?
2. Why does each field have their own class? 

I'm considering refactoring the current design approach, but I want to properly understand the decisions behind the code before doing so. Because right now, I feel that the current approach adds more complexities than it's worth

**Comment by damithc** [comment]
> I'm considering refactoring the current design approach, but I want to properly understand the decisions behind the code before doing so. Because right now, I feel that the current approach adds more complexities than it's worth

@tankh99 It is good that you want to find the rationale before you change the current design. It's a good application of the [Chesterton's Fence Principle](https://fs.blog/chestertons-fence/)

Some options:

1. See if the rationale is documented in the developer documentation or code comments.
2. Dig into the Git and GitHub history to find if there any clues there e.g. commit message of the relevant commit, or the discussion in the relevant PR. Git blame feature can help you locate the relevant commit. 
3. Try to speculate the possible motives, get views from other developers.
4. These days, you can ask AI tools.
5. Play it safe and delay the refactoring until you have worked with the code for a while, in case the reason becomes apparent after working with the code for a while.
6. Tentatively refactor it, to see the effect. Sometimes this helps you discover why the code was in the original form in the first place.
7. Go ahead and refactor it, but do it in a way it can be easily reverted later e.g., break the refactoring into a series of small/medium stand-alone design changes and do them as separate PRs (or separate commits) so that they can be reverted later, if needed. 

Trying option 3 above, others, feel free to pitch in if you have your views or if you've found out the answer to these questions.

> Can I ask what is the rationale for some of the code quality decisions in the tP sample code?
> 
> 1. Why does each command have their own class?
> 2. Why does each field have their own class?

**Comment by tankh99** [comment]
1. I looked through the git history and it seems that Command classes were there from the initial draft
2. For the attribute classes, I realises they're there to enforce immutability 

I now understand attributes, though I'm still unsure of the rationale of Command classes

**Comment by damithc** [comment]
> I now understand attributes, though I'm still unsure of the rationale of Command classes

@tankh99 I believe this particular design was inspired by the _Command Design Pattern_. Whether it is justified is still open for debate.

**Comment by tankh99** [comment]
Thank you @damithc for your response! I'm still a bit on the fence for attributes, but I think we'll follow the convention for now. I'll close this issue now since there's no discussion
