### ISSUE TITLE
chatbot behaviour question

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#52]
does our outputs and inputs need to be exactly as stated in the levels 1-6?

**Comment by lhy-hoyin** [comment]
Hello, I am a senior from a previous batch who took this module. Below is my opinion, so its probably better to see what your lecturer says.

I believe that it does not have to be exactly the same. One purpose of iP is to help bring up your competency level so that the tP is manageable. This is done by guiding your through the different levels so that you are able to come up with features for iP.

Since this module isn't about seeing your ability to mimic the sample iP, but rather see your ability to implement (reasonable) features, I would think it is reasonable to think the inputs and outputs does not need to be exactly as stated. (Furthermore, I do recall creativity being encouraged, i.e. you are encouraged to personalized your "chatbot".)

**Comment by damithc** [comment]
@bgopi23 No, as per the tip given below (from https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/projectDuke/index.html#level-1-echo )

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/5582e62c-16b0-4404-acb7-2d1b0813a1ff)

**Comment by bgopi23** [comment]
thank you
