### ISSUE TITLE
Should we use enums for commands?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#53]
I am thinking about using enums for commands, but I realised that this would require a refactor as all my functions that take in a command expect a type String. I have a few ways to approach this, but I'm not sure if this is very much worth the refactor
1. Refactor all functions to accept enum of Commands - But this would limit the helper function to only be able to accept Commands enum which I don't think is very extensible
2. Call Commands.LIST.getCommand() where getCommand() is a function to convert the enum to string - I don't really like this syntax because it breaks the purpose of the enum

Is it worth refactoring to use enums?

**Comment by lhy-hoyin** [comment]
Hello, I am a senior from a previous batch.

I shall not comment to much on your question while I give your peers a chance to think about it and discuss (you probably can add a `for-Discussion` tag to this issue).

---

>  I don't really like this syntax because it breaks the purpose of the enum

Separating the enum from a string _can_ have its benefits.

Consider this, you are task to refactor an existing software to support multiple languages. 

Assuming that the existing software did not use any enum, you would then have to go through the whole source code, find lines which checks for keywords, and add in additional keywords (of the other languages). That is going to be a lot of work (even more soft if the project is big), making the software hard to scale.

On the contrary, if the existing software used enum instead of string. Then the change is simpler: you just need to find the function that maps the string to enum and add in additional keywords (of the other languages). The change is easy and localized (to one function) hence improving scalability.

**Comment by damithc** [comment]
@tankh99 This is a good question for a discussion among classmates. Using enums is optional, so it is very much a question of "is it worth the effort?"
Thanks for inputs so far @lhy-hoyin

**Comment by drustanyjt** [comment]
@tankh99 the benefits of enums were already mentioned by @lhy-hoyin  posters mentioned a benefit of using enums already. In terms of effort, I personally feel ChatGPT / copilot is prefect for refactoring things like this (I used it for this task and wrote about it in my `AI.md`). For the sake of getting familiar with Java syntax you might want to do this manually, but in real life projects I would definitely opt for some kind of AI-assisted code generation to do this kind of refactoring.

**Comment by tankh99** [comment]
Thanks all for your inputs! I'm already convinced on the benefits of enums
