### ISSUE TITLE
Github CI running code that doesn't exist

### ISSUE THREAD

**Issue by RyanNgWH** [nus-cs2103-AY2324S2/forum#544]
The Github CI seems to be running previously committed code that no longer exists.

The same Gradle command builds successfully locally and I have tried re-running the CI multiple times but to no avail. Will be grateful to anyone who can assist me with this!

## Github CI
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/44436551/ee819649-7222-4b95-893d-9fdbd609741b)

## "Problematic" File (Can be found [here](https://github.com/RyanNgWH/tp/blob/Enhancement-SearchFields/src/main/java/seedu/address/logic/commands/AddCommand.java))
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/44436551/69a39f1a-08a1-462a-855e-b242d9096a3b)
> Note that the file only has `85` lines, but the errors are occurring at lines `88`, `92` & `96`

### Additional Information
The CI was previously passing and only randomly started failing once I made some commits that changed nothing but the formatting of the javadocs (particularly this [commit](https://github.com/AY2324S2-CS2103T-T17-3/tp/pull/77/commits/8446c078eda1212c2c27b523da9ce23107c1a70a))

The previous commit that passes the CI can be found [here](https://github.com/AY2324S2-CS2103T-T17-3/tp/pull/77/commits/30aef4e18b47e30f0a3f639cb809c931c913945f)

**Comment by damithc** [comment]
@RyanNgWH If I remember correctly, the CI runs based on the state of the code when you merge this branch to the master branch (i.e., it check if everything will be fine when this PR is merged). So, what matters is not just the `AddCommand` class in your branch but also the `AddCommand` in the latest master branch, which has 128 lines.
One possibility: The reason your PR started failing suddenly is because some code was merged to the master branch recently that makes the code in your branch no longer correct.

**Comment by RyanNgWH** [comment]
Oh that is really good to know and was exactly the issue! Thank you so much!
