### ISSUE TITLE
CI failing for test cases where I did not touch 

### ISSUE THREAD

**Issue by chewbum** [nus-cs2103-AY2324S2/forum#545]
I added two different test classes for an add command and somehow, all the other test cases are failed. Did anyone face a similar problem?
PR link: https://github.com/AY2324S2-CS2103-F08-1/tp/pull/104

<img width="347" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/111036673/9542a239-121b-48a6-8c92-a7d86c99fc3c">

**Comment by damithc** [comment]
@chewbum It might help to share the link to the PR so that others can go and check all the relevant details.

**Comment by yisiox** [comment]
@chewbum At a cursory glance, your changes to `Person.java` caused `testutil/TypicalPersons.java` to fail to initialize `JAMAL` due to a bug in `Person::withDefaultMeetingA`. This meant that none of the typical persons, specifically `AMY`, "do not exist" which is what causes the very first error in your screenshot. I believe most of the failing tests are due to this.

**Comment by chewbum** [comment]
@yisiox 
I am not even calling withDefaultMeetingA though, I am quite confused as i only added two small methods to Person.java and it is breaking everywhere.

**Comment by damithc** [comment]
@chewbum Are the tests failing locally as well? If yes, you can try to debug (using IDE debugging features) the first test that fails.
If they are not failing locally, you can update your branch (i.e., merge the master branch to your branch) and run the tests locally again to see if they still pass.

**Comment by seanfirefox** [comment]
Hi senior here,

as what prof @damithc has mentioned, you should debug using your IDE as there are more logs.

```
org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.IllegalArgumentException: Date must be in dd-MM-yyyy HH:mm format.
Date & time must be after the current time.
Time of appointment must be on the hour.
	at seedu.address.commons.util.AppUtil.checkArgument(AppUtil.java:39)
	at seedu.address.model.meeting.Meeting.<init>(Meeting.java:48)
	at seedu.address.testutil.MeetingBuilder.build(MeetingBuilder.java:72)
	at seedu.address.testutil.PersonBuilder.withDefaultMeetingA(PersonBuilder.java:107)
	at seedu.address.testutil.TypicalPersons.<clinit>(TypicalPersons.java:60)
```

Notice that date and time must be after the current time, and the date and time you set for meeting A and B are definitely before the current time. Also, you call the default meeting functions when you set your `TypicalPersons`.

Just change the date and time from `05-03-2024 13:00` to something else like `05-05-2024 13:00` and the tests will pass (I only tested `LogicManagerTest` and `AddCommandIntegrationTest`). If there are any more errors with the other tests, try debugging them yourself with the IDE.
```
public PersonBuilder withDefaultMeetingA() {
        this.meetings.add(new MeetingBuilder()
                .withClient(JAMAL)
                .withDescription("Financial Aid Document Submission")
                .withDateTime("05-03-2024 13:00").build());
        return this;
    }
```

**Comment by yisiox** [comment]
This compiles, but will throw an error when ran:
```java
public class bar {
    public static void main(String[] args) {
        new foo();
    }
}

class foo {
    private static int f() {
        throw new RuntimeException();
    }
    private static int x = f();
}
```
As I understand this is essentially what is happening to `TypicalPersons` which calls `withDefaultMeetingA` which has a value that fails the newly added condition of not being before the current time. Many tests import from `TypicalPersons`, which is why so many broke. The fact that it compiles and runs without error if the the foo class is instantiated is also why some of the other tests did not break.

**Comment by JerryWang0000** [comment]
I assume you are using `Assert` in your test methods. My trick is to only choose one between the actual and expected output to consider. If you have confidence that your implementation is correct, it is more likely that the newly added test classes have bugs. They are harder to detect than the main codes. IDE can tell the corresponding output by the test codes.

**Comment by chin-herng** [comment]
Hi, I am tagged so I figured that I might as well pitch in, despite the fact that this seems to have been resolved. It might be helpful to contribute my process of figuring out the cause of the error. I came to the same conclusion as @seanfirefox did.

I cloned the fork, pulled the problematic branch and `checkout`ed the problematic commit `1a033d06` (according to the PR timeline, this is the commit right before the PR is mentioned in this issue). I tried to run all tests and indeed 99 out of 310 tests have failed.

In particular, the `execute_storageThrowsAdException_throwsCommandException` test failed. The IDE shows that an `ExceptionInInitializerError` has been thrown. I searched online for information relevant to this error and found this [resource](https://www.baeldung.com/java-exceptionininitializererror) helpful. It turns out that the `Caused by: ...` section of the error message shows exactly which line of the static initializer is causing the error.

```
Caused by: java.lang.IllegalArgumentException: Date must be in dd-MM-yyyy HH:mm format.
Date & time must be after the current time.
Time of appointment must be on the hour.
	at seedu.address.commons.util.AppUtil.checkArgument(AppUtil.java:39)
	at seedu.address.model.meeting.Meeting.<init>(Meeting.java:48)
	at seedu.address.testutil.MeetingBuilder.build(MeetingBuilder.java:72)
	at seedu.address.testutil.PersonBuilder.withDefaultMeetingA(PersonBuilder.java:107)
	at seedu.address.testutil.TypicalPersons.<clinit>(TypicalPersons.java:60)
```

As per the resource given, `<clinit>` is the class initializer method. Line 60 in `TypicalPersons.java` seems to be part of a statement that is causing the issue.

```java
public static final Person JAMAL = new PersonBuilder().withName("Jamal").withPhone("88888888")
            .withEmail("jamal@example.com").withAddress("little india").withDefaultMeetingA().build();
```

Following the stack trace, `withDefaultMeetingA` calls `MeetingBuilder#build`, which calls the `Meeting` constructor, which calls `checkArgument`, which throws an `IllegalArgumentException`. Here is the `checkArgument` method:

```java
public static void checkArgument(Boolean condition, String errorMessage) {
    if (!condition) {
        throw new IllegalArgumentException(errorMessage);
    }
}
```

Looking into the `Meeting` constructor, we know that `isValidDateTime(dateTime.format(formatter))` evaluated to false, where `dateTime` has the value of `LocalDateTime.parse("05-02-2024 13:00", formatter)` and `formatter` has the value of `DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm")`.

The `isValidDateTime(dateTime.format(formatter))` method essentially checks whether `"05-02-2024 13:00"` is before `LocalDateTime.now()`, and returns false if so. Now we see why `checkArgument` throws an `IllegalArgumentException`, ultimately causing the `ExceptionInInitializerError` and the test cases to fail.

> I am not even calling withDefaultMeetingA though, I am quite confused as i only added two small methods to Person.java and it is breaking everywhere.

We can figure this out by looking at where exactly did `ExceptionInInitializerError` occurs. The IDE shows that it occurred in the `assertCommandFailureForExceptionFromStorage` method, on line 170. This method is being called by`execute_storageThrowsAdException_throwsCommandException`, which is one of the tests that will be run when we run all tests. On line 170, the test makes use of `AMY` from the `TypicalPersons` class, so the class initializer method (the so-called `<clinit>`) of `TypicalPersons` is being executed, which will initialise all the static variables in the class, among which is the problematic `JAMAL`, which calls `withDefaultMeetingA`.

**Comment by SPWwj** [comment]
Hi @chewbum, I am a senior from the previous batch. It seems you have identified the issue causing the bug and fixed it. Please remember to share your findings as they can benefit others, and make sure to close the issue.

In addition to the answers provided by others, ensure that the new test you've added does not affect other test cases by modifying the test values used for other test cases.

**Comment by damithc** [comment]
Thanks @yisiox @seanfirefox @chin-herng @SPWwj @JerryWang0000 for pitching in to help @chewbum 
And thanks @chin-herng for very detailed investigation report 💯

**Comment by chewbum** [comment]
Thank you @chin-herng @seanfirefox @SPWwj @JerryWang0000  @yisiox  for the help! I have fixed it together with my group. What happened basically was that we had a cyclic dependency between Person and Meeting which resulted in our Typical Persons, Jamal and Chad specifically causing the Chicken Egg problem which caused the error throughout the classes. We ended up fixing the test cases by returning a Person object in our MeetingBuilder instead. Really appreciate all your help on this!!!

**Comment by lhy-hoyin** [comment]
Hi @chewbum,

Can I check if you had the chance to try the suggestions made by @seanfirefox and @yisiox? Are you still facing problems with your code? If so, I can help to look into the issue too.

If the issue is resolved, it would be great to close this issue too. Thank!
