### ISSUE TITLE
Coupling

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#563]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/a6347c41-e546-416c-9937-7286c3d6ac38)
What does C mean?

**Comment by tankh99** [comment]
Because the more coupled components are, the more likely it is to suffer from regressions as you add more code, since with highly coupled components, changing one thing may negatively impact the other coupled thing. Therefore, tests become even more important to prevent such regressions from happening in the first place

**Comment by baskargopinath** [comment]
thnks @tankh99

**Comment by damithc** [comment]
> Because the more coupled components are, the more likely it is to suffer from regressions as you add more code, since with highly coupled components, changing one thing may negatively impact the other coupled thing. Therefore, tests become even more important to prevent such regressions from happening in the first place

Yes, @tankh99 is correct. The more likely regressions are, the more often we should do regression testing, which is only practical if they are automated.
