### ISSUE TITLE
Cohesion

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#564]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/3acda31f-0fbb-4339-9c49-8cb7dfc6a02a)

Why is b correct?
if cohesion means how strongly related components are, and we try to isolate the GUI, doesnt that mean cohesion is lower?

**Comment by lynnetteeee** [comment]
I found this part quite tricky too... this is my interpretation but let me know if I understood it wrongly! 

I understood 'components' as parts of the code that focuses on various responsibilities, and 'cohesion' as the degree to which the components belong together, directed towards performing a single task. If theres one task (in this case, to interact with user), as part of SoC principle, we would be letting one component (GUI class) handle it to prevent functional overlap rather than combining with another class (with an unrelated responsibility). 
<img width="544" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/dda26ef5-c19c-46ce-9220-8ce816f6b587">
From the explanation ^, we can see that by isolating the GUI class, we know the GUI class' sole responsibility IS in user interaction, thus all the code in GUI class are highly related to perform this same task, achieving high cohesion.

**Comment by baskargopinath** [comment]
i see, thank u @lynnetteeee

**Comment by damithc** [comment]
@bgopi23 To add, cohesion applies to what's _inside_ of a component whereas coupling is something _between_ components.  So, when we say we want each component to be cohesive, we mean each component should contain things strongly related to its job only.
I suspect your initial doubt was a result of thinking cohesion as something that happens _between_ components.
