### ISSUE TITLE
level-5 error handling

### ISSUE THREAD

**Issue by taeewonnn** [nus-cs2103-AY2324S2/forum#57]
Is it okay if my chatbot operation terminates after handling the error? @damithc

**Comment by damithc** [comment]
@taeewonnn We expect you to decide i.e., you can consider the options and decide which is the best choice -- factor in things like implementation effort, impact on user experience.
This is also a good aspect to discuss among classmates.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Personally, I felt like gracefully catching the error and providing the user with feedback instead of terminating gives the user the best experience, as it would prevent the user from having to restart the program again. 

In addition, it would also serve as good practice with exception handling for the tP.

Just my two cents!

**Comment by taeewonnn** [comment]
> @taeewonnn We expect you to decide i.e., you can consider the options and decide which is the best choice -- factor in things like implementation effort, impact on user experience. This is also a good aspect to discuss among classmates.

Alright thank you!

**Comment by taeewonnn** [comment]
> Personally, I felt like gracefully catching the error and providing the user with feedback instead of terminating gives the user the best experience, as it would prevent the user from having to restart the program again.
> 
> In addition, it would also serve as good practice with exception handling for the tP.
> 
> Just my two cents!

True that would be better for the user. Thank you!
