### ISSUE TITLE
What is the best way to prepare for finals?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#581]
Is reading the textbook and practicing tutorials/quizzes sufficient?

**Comment by kiwibang** [comment]
Hi, am a senior dropping in from last semester's batch, and would like to give some tips that worked for me :)

Yes, exam questions will be quite similar to the quizzes, reviewing them is a good way to prepare

Reading the textbook definitely helps, but to ensure that you are fully prepared, I recommend that:
- You understand the content well (understand the rationale, rather than rote memorization)
- Know roughly where each category is placed in the textbook, so you can find it quickly during the exam
- A good PDF reader (specifically one with good CTRL-F capabilities is a big plus)

Reviewing the tutorials, and perhaps redoing tutorials that are most relevant to the exam
- I would recommend redoing T8 and reviewing the answer (I believe your TA has uploaded the answer to MS Teams), since T8 is about drawing UML diagrams accurately, which is much needed for part 2 and part 3 of the exam
- If you have the time, at least review the other tutorials after T8 :)

Last but not least:
- Get enough sleep (at least 8 hours+)!!! This ensures that your brain is in tip-top condition, hence I don't recommend staying up late to cram! (A little hypocritical of me writing this at 1am in the morning but hey I don't have final exams later today 😜)

**Comment by TiwKangXu** [comment]
Hi, I'm a senior dropping in from last semester's batch, and would like to give some tips that worked for me :>
For Diagrams:
- Get familiar with the diagrams (Class Diagram, Object Diagram, Sequence Diagram etc.)! 
- There aren't many practices, so it is good to redraw those in the tutorial questions!
- Practices are important for you to get a feeling of from which part you should start drawing!
- Don't get confused of the formats of diagrams, as they are quite similar! 
- Don't get nervous, as you don't want to draw something too abstract that even Picasso cannot recognize!

For theory MCQ/MRQ:
- Ya, just be familiar with the content and you're good to go!

GOOD LUCK AND HAVE ENOUGH SLEEP!! (A little hypocritical of me writing this at 2am in the morning but hey I don't have final exams later today 😜)

**Comment by baskargopinath** [comment]
thanks alot @TiwKangXu @kiwibang

**Comment by oeggy03** [comment]
Hey, another senior chiming in here. I think that the previous commentors have already left a lot of good points so not much for me to add. 

But one thing I did last sem was to summarise all of the textbook content for each section, while keeping the important infomation. This helped me reduce the number of pages from over 250(?) to just under 40 pages. I also added a content page to my summarised textbook, which helped me navigate through the content much more easily.

This took me around 2 days (which might be asking for a lot :")) but it really helped me internalise the important points of each topic and section, since I was forced to read through them. 

Also yes, get enough sleep :)

**Comment by baskargopinath** [comment]
@damithc prof could you please give your advice for this as well if possible?

**Comment by baskargopinath** [comment]
@oeggy03 thank u

**Comment by damithc** [comment]
> @damithc prof could you please give your advice for this as well if possible?

@bgopi23 There will be an exam briefing later. In the meantime, my somewhat predictable general advice is to follow instructions faithfully and do the course tasks sincerely without taking shortcuts (e.g., study the weekly topics first and try your best in Canvas quizzes, try tutorial tasks before attending the tutorial).  That approach should help you score well for the entire course, not just the exam, and get the best value out of the course as well.

**Comment by baskargopinath** [comment]
i will do this, thank u prof @damithc
