### ISSUE TITLE
Objects.requireNonNull() or assertion?

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#583]
Suppose we have an object `x` which should not be `null`. To practice defensive programming, which is better: `Objects.requireNonNull(x)` or `assert x != null`?

**Comment by yashpola** [comment]
It seems like `Objects.requireNonNull(x)` is better since it is explicitly designed for parameter validation in methods and constructors. Additionally, assert statements seem to be better left out of production code since we can still recover from exceptions thrown by `Objects.requireNonNull(x)` whereas we're meant to use assertions in testing and bug-fixing and allow exceptions from assertions to happen

Moreover `Objects.requireNonNull(x)` being a method instead of a keyword like `assert` allows us to pass in the results of another methods directly into the null-check instead of create a variable first and then compare that variable using `assert`

https://stackoverflow.com/questions/60712593/should-you-assert-not-null-with-the-assert-statement-in-production-code

**Comment by tankh99** [comment]
To add on, the former is better, because assertions won't always trigger since they require additional application configuration where as requireNonNull usually always works
