### ISSUE TITLE
Which code is a better application of SLAP?

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#593]
Out of the two classes below, which is better?

```
class A {
    void doStuff() {
        // ...
    }

    void doMoreStuff() {
        // ...
    }

    void doSomething(boolean b) {
        doStuff();
        if (b) {
            doMoreStuff();
        }
    }
}
```
```
class B {
    void doStuff() {
        // ...
    }

    void doMoreStuffIfB(boolean b) {
        if (b) {
           // ...
        }
    }

    void doSomething(boolean b) {
        doStuff();
        doMoreStuffIfB(b);
    }
}
```

Initially, class `B` seems to be a better option as `doSomething()` only has 1 layer of abstraction. However, on closer analysis, `doMoreStuffIfB()` is more restrictive than `doMoreStuff()`, which could potentially be used by another method with a different condition. Any thoughts?

**Comment by damithc** [comment]
@aureliony It might be easier if you replace A and B etc. with real examples, in case the answer depends on the context as well.

**Comment by PallonCX** [comment]
Hi, in my opinion, if `doMoreStuff()` is meant to be a general function that can be used by a number of methods, it will indeed be good to let it be less restrictive. On the other hand, if `doMoreStuff()` is a private helper method only for `doSomething()`, then it make sense to let it be restrictive in order to maintain the single layer of abstraction in `doSomething()`.

As an alternative, perhaps you can use `class B`, but add another function called `doMoreStuffIfNotB()`. E.g.
```java
void doMoreStuffIfNotB(boolean b) {
    if (!b) {
       // ...
    }
}
```

Then any method that needs them, e.g. `doSomething()` can do:
```java
void doSomething(boolean b) {
   doStuff();
   doMoreStuffIfB(b);
   doMoreStuffIfNotB(b);
}
```
