### ISSUE TITLE
Why must `primaryStage.show()` be called before filling inner parts?

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#601]
I'm referring to the comment in this file: https://github.com/nus-cs2103-AY2324S2/tp/blob/b896eb01c1e50e6acdf7f9636ca7d5785729c954/src/main/java/seedu/address/ui/UiManager.java#L44

What's the technical reason for this? I tried calling `fillInnerParts()` before `primaryStage.show()`, and it still worked as expected.

**Comment by lhy-hoyin** [comment]
Hello, I'm a senior from previous batch.

My guess would that the inner UI elements has some kind of dependency on `show()`, at least back when the comment was inserted [8 years ago](https://github.com/nus-cs2103-AY2324S2/tp/blame/b896eb01c1e50e6acdf7f9636ca7d5785729c954/src/main/java/seedu/address/ui/UiManager.java#L44). The code might have since been changed then, to the point that it does not really matter now. That would explain why it works as expected even when `fillInnerParts()` is called before `show()`.

I have elaborated a bit below to give you a better idea. Hopefully, it answers your question too.

---

Going back to the [commit](https://github.com/nus-cs2103-AY2324S2/tp/commit/d96694832ac11cc75fdebd38bc7df632d8e9e8f0) which wrote the comment:

```java
// Ui.java
mainWindow = MainWindow.load(primaryStage, config, prefs, mainApp, this, modelManager, browserManager);
mainWindow.show(); //This should be called before creating other UI parts

mainWindow.fillInnerParts();
```

```java
// MainWindow.java
public void fillInnerParts() {
    personListPanel = PersonListPanel.load(primaryStage, getPersonListPlaceholder(), modelManager, browserManager);
    statusBarHeader = StatusBarHeader.load(primaryStage, getHeaderStatusbarPlaceholder());
    statusBarFooter = StatusBarFooter.load(primaryStage, getFooterStatusbarPlaceholder(), addressBookName);
    browser = loadBrowser();
}
public void show() {
    primaryStage.show();
}
```

You can see that the UI elements takes in `primaryStage` as one of its parameter, thus hinting at some kind of dependency on the state of `primaryStage`. Of course, you could dive deeper in and debug if that is actually the case, but I shall leave that to you.



Presently, looking at the latest [commit](https://github.com/nus-cs2103-AY2324S2/tp/tree/bd48d597b72da7c0570699a0912f834f619f53a9) (as of the time of writing):

```java
// UiManager.java
mainWindow = new MainWindow(primaryStage, logic);
mainWindow.show(); //This should be called before creating other UI parts
mainWindow.fillInnerParts();
```

```java
// MainWindow.java
void fillInnerParts() {
    personListPanel = new PersonListPanel(logic.getFilteredPersonList());
    personListPanelPlaceholder.getChildren().add(personListPanel.getRoot());

    resultDisplay = new ResultDisplay();
    resultDisplayPlaceholder.getChildren().add(resultDisplay.getRoot());

    StatusBarFooter statusBarFooter = new StatusBarFooter(logic.getAddressBookFilePath());
    statusbarPlaceholder.getChildren().add(statusBarFooter.getRoot());

    CommandBox commandBox = new CommandBox(this::executeCommand);
    commandBoxPlaceholder.getChildren().add(commandBox.getRoot());
}
void show() {
    primaryStage.show();
}
```

As you can see, there is no (obvious) dependency on `primaryStage` inside of `fillInnerParts`. This might explain why it currently works as expected.

**Comment by aureliony** [comment]
Just a small update, I have encountered an example where fillInnerParts() must be called after showing the stage. Details are in this commit: https://github.com/AY2324S2-CS2103T-W12-3/tp/pull/171/commits/0856c4540b97fb8e8d71a7a6e54c92bf48422a0f
