### ISSUE TITLE
Feature Freeze In Light of Feature Flaws

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#630]
During the PE Dry Run one of the **types** of bugs that can be report are **Feature Flaws**.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/f3502654-64b7-497a-b5fb-cf09b4c3872e)

 If there are valid Feature Flaws reported during the PE Dry Run, are we allowed to change them in, even if this means adding new features that did not previously exist, while working on v1.4? Since these feature flaws could affect the actual PE grading, it feels like it would be important to add them.

**Comment by damithc** [comment]
@drustanyjt That is not allowed, as that would undermine the feature freeze. But there are some remedies available - see Q2 of [this FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=FAQs%20on%20what%20is%20allowed%20during%20the%20feature%20freeze).

**Comment by camille-readbean** [comment]
https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#2-start-fixing-ped-bugs-before-the-tutorial


Q2: Will we be penalized for feature flaws not fixed during the feature freeze?

A: Product design is hard, and achieving a very good design takes experience, skill, and multiple iterative refinements. Hence, having some feature flaws at this stage is natural. Accordingly, feature flaws will not be penalized In the following cases:

  - If the feature flaw will be fixed by an item you listed in the Planned enhancements DG section (as mentioned above).
  -  After the feature flaw is reported during the PE, you successfully argued it as 'not in scope' (i.e., fixing that flaw is of lower priority than the work done already, and hence it is justifiable to be postponed to a future version). Reporters of such bugs will earn partial credit.

In addition, you can mitigate the impact of feature flaws and thus lower its severity by tweaking the UG (e.g., explain the feature better, clearly state the limitations and guide users to work around those limitations)

**Comment by drustanyjt** [comment]
Thanks everyone for clarifying!
