### ISSUE TITLE
Clarifying if changing code is allowed in this case

### ISSUE THREAD

**Issue by Arixeyeion** [nus-cs2103-AY2324S2/forum#694]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122505234/a6b9a7ad-2f7d-4df4-84c8-87992e235344)

Before PE-D, we have declared in the UG that the file will be saved as `FINDvisor.json`. However, a bug was reported that the file is still saved as `addressbook.json`, in this case, are we allowed to change the code to fix this issue?

**Comment by damithc** [comment]
@Arixeyeion The UG indicates an intent to have this feature, but there is still the question of was it ever implemented. Also, the current behavior, while different from the UG, doesn't hinder the normal operation/usage of the app. So,
* if you have clear evidence (in the code) that this feature was implemented but the implementation was buggy, you can correct it.
* Otherwise, you can update the UG to match the current behavior.

**Comment by Arixeyeion** [comment]
ok thank you prof!
