### ISSUE TITLE
Bug Fix clarification

### ISSUE THREAD

**Issue by g-tejas** [nus-cs2103-AY2324S2/forum#707]
We've read over the PE-D FAQ, but we are still unsure if we are allowed to make the following fix. Our UserGuide mentions that we only allow valid emails, but there was a bug reported that allows "hello@example" which is an invalid email, which is an error in our REGEX validation, are we allowed to fix this? Sorry if this was asked already!

**Comment by damithc** [comment]
@g-tejas If you app reject a valid email, it's a bug that can be fixed in v1.4. But if the issue is that it also accepts certain invalid emails, it's not eligible to be fixed during the feature freeze. Instead, you can update the UG to match the current behavior (e.g., not mention email validation at all or mention that some level of validation is in place but it is up to the user to ensure the email is valid).

**Comment by g-tejas** [comment]
Thank you!
