### ISSUE TITLE
Clarification on feature freeze on JSON issue

### ISSUE THREAD

**Issue by chiageng** [nus-cs2103-AY2324S2/forum#724]
Our team has received issue which mentioned about JSON file.

When JSON file is imported, some of the data is not validated before creating into AddressBook. Is this considered a feature flaw?

If it is, are we considering tag validation and date validation for JSON file as two separate feature flaw or JSON validation as one feature flaw as our planned enhancement? 

One issue also mentioned that we should provide sample data to first time user. Is this consider a feature flaw? Can we now provide a set of sample data in form of JSON to first time user?

**Comment by damithc** [comment]
@chiageng 

> Our team has received issue which mentioned about JSON file.
> 
> When JSON file is imported, some of the data is not validated before creating into AddressBook. Is this considered a feature flaw?

How did wrong data get into it in  the first place? If it was by manual editing, you can simply state in the UG that if the user choose to edit the data file, it is up to the user to ensure the validity of data.


> If it is, are we considering tag validation and date validation for JSON file as two separate feature flaw or JSON validation as one feature flaw as our planned enhancement?

If fixing one fixes the other automatically, it is considered as one bug/feature. Otherwise, two.


> One issue also mentioned that we should provide sample data to first time user. Is this consider a feature flaw? Can we now provide a set of sample data in form of JSON to first time user?

Yes, this is not a bug but an enhancement, unless the data file was there already but was not picked up the app due to an error in the code.
