### ISSUE TITLE
Is fixing a behaviour allowed for v1.4?

### ISSUE THREAD

**Issue by ryanlimdx** [nus-cs2103-AY2324S2/forum#734]
Hi prof! I have 3 questions pertaining to this:
1. In the following screenshot, is it ok to fix the behavior such that regardless of case, only one variation is allowed? For example, the nurse can key in any one of fallRisk, FallRisk, FALLRISK only (along with other tags if required), otherwise the system will throw an exception? In our UG, we broadly define tags as: "Optional tags to categorize the patient by health condition or other descriptors. Tags should be alphanumeric and can be used multiple times."

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/91833948/53f1a46f-3c04-486c-a70a-7bc6b3642c94)
2. Are we allowed to fix our platform's behavior to accept common names (such as names with "d/o", "s/o")?
3.  Similarly, are we allowed to fix limitations from the date time class such as it allowing 30/02/2024 even though it is an invalid date?

Thank you for taking the time to go through the cases.

**Comment by ryanlimdx** [comment]
Also to clarify, we do have some issues with text wrapping as well. For example, if the names/ tags are too long (~100 characters for example), it will go past the boundary of the screen. Even when expanding the screen, it seems that the text will still not be fully shown. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/91833948/54dfc7c9-c486-45b9-8652-cff0e5394c77)

Since viewers will not be able to "see the full text in any way", we are able to fix this right? I am slightly confused as later on, it is mentioned that this may qualify as a nice to have as well. Thank you!

**Comment by damithc** [comment]
@ryanlimdx 
1. Seems to me your add command is case sensitive but the find command is not. This is not strictly incorrect, as search functions can be more permissive in order to find more matches. As per Q7 of FAQ in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html tweaking the case-sensitivity is considered an enhancement. Instead, you can explain in the UG that tags are case sensitive.
2. Unless it is critical that the name in your app matches the exact legal name of the person, you can ask users to use a workaround for such cases. Also see Q5.
3. Q5 addresses this as well.
4. As per Q8, during the feature freeze, we should not change code just to cater for 'extreme' values. So, allowed only if the problem in concern affects non-extreme values as well. In this case, your UG can inform users to limit the name to a certain length, as longer names are not handled well by the UI.

**Comment by ryanlimdx** [comment]
@damithc 
I see, thank you! For point 2, from the perspective that our app is a healthcare platform for nurses in Singapore, being able to match the exact legal name is critical in our opinion. Will we be allowed to fix only the name inputs in this regard? Otherwise, we will be sure to update our UG to reflect the workaround for the naming. Thank you so much for taking the time to reply!

**Comment by damithc** [comment]
> I see, thank you! For point 2, from the perspective that our app is a healthcare platform for nurses in Singapore, being able to match the exact legal name is critical in our opinion. Will we be allowed to fix only the name inputs in this regard?

@ryanlimdx yes, in that case you can update the code to accept such names.

**Comment by ryanlimdx** [comment]
Thank you prof!
