### ISSUE TITLE
Week 1 Quiz Qn 15

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#82]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/1ff2b51e-1b09-4ac6-aad8-65f7a19f3a35)
Why is Object class itself a descendant of itself?

**Comment by damithc** [comment]
Good catch :-p
It wasn't meant to be a 'trick question', so '(except the `Object` class itself)' is implied.

**Comment by E0735389** [comment]
Personally, I automatically interpreted "descendant" as "non-strict descendant" while reading that question based on the context, and did not think too much about it.

I decide to look up the Java specification. https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.1.4 The formal term used is "subclass" instead of "descendant", and it indeed only consider strict subclass.

> The superclass relationship is the transitive closure of the direct superclass relationship.

and

> A class is said to be a direct subclass of its direct superclass, and a subclass of each of its superclasses.

I suppose both convention is fine. (while C++ uses `operator<` as the canonical comparison operator, in mathematics, a poset uses $≤$ as the canonical comparison operator)

**Comment by UdhayaShan1** [comment]
Thanks for the input! @E0735389 

Guess its was supposed to be just a general question hahah

Will close
