### ISSUE TITLE
severity.High definition

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#882]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/c8fb2a0a-0a61-429a-82be-ca0dd54f4b33)

Here it appears, even if the impact is huge for a small subset of users its considered high severity but here,
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/99b716aa-75c4-4195-9000-096069f6811b)

Its defined as a flaw that affects most users, but it is unlikely most users may encounter this problem. I am confused on which is the important factor, disastrous or the likelihood of user facing it?

**Comment by damithc** [comment]
@UdhayaShan1 There is no fixed priority order between the two. You can choose based on which one seems to having the more importance in the given situation. In this specific case, the fact that this disaster can happen to _any_ user pushes the severity higher. 

Another way to think about it is, being told of the bug, would _most_ potential users say 'Oh? Then I'm going to use this app!`

Compare that with another bug which wipes out the entire data file after reaching 10,000 contacts. That bug is unlikely to turn away most users.

**Comment by UdhayaShan1** [comment]
Thanks!, will keep this in mind
