### ISSUE TITLE
System as an actor

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#895]
We are told that it's not recommended to put a system as an actor in use case diagrams, however, what if it is an actor? Is it still strictly always outside the system?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/e2725a1e-ce85-4419-86b3-064b8fdae316)

**Comment by E0735389** [comment]
If I understood correctly,
* it's not true that you should put **a** system as an actor, it is just that you should not put the system that is *the software you're developing itself* as an actor. If you're developing an API, then "automated scripts interacting with the API" might as well be an actor.
* the intention is that the things described in use case diagrams describes *high level* interactions (i.e. one bubble represents a whole use case). So an action like "system notifies user of new messages" would be too granular, since often the next action in the use case would be "user check new messages" or "user discard the notification".

**Comment by damithc** [comment]
> * it's not true that you should put **a** system as an actor, it is just that you should not put the system that is _the software you're developing itself_ as an actor.

Yup (thx @E0735389)

**Comment by tankh99** [comment]
> If I understood correctly,
> 
> * it's not true that you should put **a** system as an actor, it is just that you should not put the system that is _the software you're developing itself_ as an actor. If you're developing an API, then "automated scripts interacting with the API" might as well be an actor.
> * the intention is that the things described in use case diagrams describes _high level_ interactions (i.e. one bubble represents a whole use case). So an action like "system notifies user of new messages" would be too granular, since often the next action in the use case would be "user check new messages" or "user discard the notification".

Thank you @E0735389. From what I now understand, it's that the system that we're modelling itself should not be part of the use case system. And even then, its use case interactions would be too granular to be meaningfully modelled in a use case diagram.

**Comment by damithc** [comment]
@tankh99 To clarify, the system we are modelling is already shown in the use case diagram as the rectangle. It should not be also shown as an actor. But other external software that the target system interacts with can be shown as actors.
