### ISSUE TITLE
Package statement

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#90]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/9ba40228-dc86-4fcf-ab5a-a9dae61da44e)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/f35fbb86-76a6-4fd8-a799-bdf79137e0a8)

Currently this is my directory structure, but I am only able to declare packages in the form of relative path

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/aa411e4e-229e-4ef1-b925-ac9a7a907918)

Doing something like in the notes, package src.main.java.utilities; will create src.main.java.utilities folder itself. Am i doing something wrong in this regard? Thanks

**Comment by benson1029** [comment]
Yes, Java packages must correspond to the directory structure. `package src.main.java.utilities;` must be placed under the directory `src/main/java/utilities`.

In your case, it's better to create a common folder (say, duke) and place all your subfolders inside that common folder. Then, you can declare packagaes like duke.tasks, duke.utilities, etc.

**Comment by damithc** [comment]
@UdhayaShan1 While we wait for more peer inputs, one thing that might help is to note that `<source folder>` (mentioned in the following screenshot) is not the same as `<project folder>`. The former resides somewhere inside the latter, and usually a standard location such as `<project folder>/src/main/java/` so that other tools (e.g., Gradle, which we will be using later) can easily identify where the source files are.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/9ba40228-dc86-4fcf-ab5a-a9dae61da44e)

**Comment by UdhayaShan1** [comment]
I think i get it , my directory is \CS2103T iP\src\main\java\utilities
My src here is java and not the 'src' in the directory. So just 
package utilities

So if  \CS2103T iP\src\main\java\<name1>\utilities

Then i would have 
package name1.utilities

**Comment by UdhayaShan1** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/00ecee15-6433-476a-82fa-147513af4d51)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/a035ed8d-2085-45b8-a4d6-0aad5354f959)

Works as expected, thanks @damithc @benson1029
