### ISSUE TITLE
PE readiness quiz: question 17 is not just a typo?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#900]
In this question:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/04358074-c3eb-41a7-8788-6d37e873dd9a)

I see it as just a cosmetic issue: it is implicitly understood by the user that the opposite of `up` should be `down` assume user has reasonable amount of English knowledge, right? Which I think makes it overwhelmingly likely for the user to just mentally ignore the typo and type the correct command?

(That is, assuming the actual application correctly handles `s/down`, but this is not written in the bug report. On the other hand if the actual application has a different typo e.g. `s/dwon`, then indeed it's possible that the user cannot sort in decreasing order)

**Comment by damithc** [comment]
@E0735389 The higher severity is because the typo is in the command syntax (not in the regular descriptive text). Commands are defined by the app, so it is not necessary to be English words, especially in an app that is likely to use shorter words to  make the commands faster to type

But yes, in this case the user might discover the correct command by guessing.
