### ISSUE TITLE
Upgrading severity

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#908]
If testers flagged some minor bugs as `severity.VeryLow` but they are not for cosmetic issues. Are we expected to bump it up to at least `Low` increasing our penalty.

Thanks

**Comment by damithc** [comment]
@UdhayaShan1 Good question. In theory, yes, you should choose the correct severity. 
In the context of the PE, we don't require you to. So, it is fine to leave as is.

If you don't change the severity selected by the tester, the tester will not have a way raise any objections about the severity of the bug later (because the tester can object only if the dev team changed a label), which means the original severity will be accepted as the correct severity of that bug.

**Comment by UdhayaShan1** [comment]
Thank you
