### ISSUE TITLE
Do we consider bug report regarding terminal for PE

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#912]
Hi, our group receives some bug reports regarding grammar error in terminal. From the course website, we are not aware that logging output in the terminal is part of the scope of bug catching. Can we get some guidance on this matter? 

Thank you in advance!

**Comment by damithc** [comment]
@PallonCX console output is a grey area, as it is in plain view of the user but not meant to be used by the user. So, issues related to the terminal are not meant to be tested in the PE, unless it is something that naturally attracts user attention e.g., a stack dump due to an error or log output that might give user the impression that something is wrong with the application.

**Comment by PallonCX** [comment]
Alright, thanks prof!

**Comment by vnnamng** [comment]
[surprised]     Nguyen Xuan Nam reacted to your message:
________________________________
