### ISSUE TITLE
Practice Paper : P3.15

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#926]
Why is Class Diagram less useful than something like sequence diagram?

<img width="1289" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/a45ccba2-ae40-4eb2-a0b7-615944e024fb">

**Comment by tankh99** [comment]
I have a similar question. To add on:

In what way does sequence diagram and activity diagram model the domain better than class diagram here?

Even if a class diagram models the solution implementation rather than the problem domain, is it not arguably more effective in modelling as it is higher-level than sequence or activity diagrams?

**Comment by damithc** [comment]
* Domain modelling can be done using domain-specific models too e.g., organization charts. Doesn't need to be UML models.

* Some models, such as sequence diagrams and activity diagrams, can be used to model both problem domain and the solution domain. 

* But in the case of class diagrams, there is a different tool (CCD) that is optimized for domain modelling.

* So, if we are asked to pick pick 4 out of these 5 tools for domain modelling, confirmed we should ditch CD, as we already have a better tool for the same job.

That said, I agree that the way this question is phrased may not point you in that direction of reasoning.

**Comment by baskargopinath** [comment]
ah i thought class diagrams is correct because CCD is a type of class diagram, but the way u explained makes sense: why do we need both when one of them is a better version of the other

Thank u prof @damithc
