### ISSUE TITLE
Scope of the Planned Enhancements when it comes to rejecting issues.

### ISSUE THREAD

**Issue by miffi** [nus-cs2103-AY2324S2/forum#959]
(I'm not sure how much I should divulge about my PE testing project, so I've kept their information anonymous)

During the PE, I made a bug about the UI of a specific command being clunky and difficult to use and proposed an alternative.

Specifically it is about the user needing to find a unique pair of indices of persons. The persons should be paired in the state of the program itself, so it didn't really make sense for me to have to provide both indices.

The team I did the PE for has a planned enhancement that they will change the program to include multiple overlapping pairing, which seems grounds for rejection. But they also mention groupings of multiple people being one part of a pair. This seems like it would need some other UI entirely and that the enhancement would rather obsolete the UI problem I'm having now rather than fix it.

So, if a planned enhancement obsoletes an issue right now instead of truly fixing it, is that fair for getting rejected?

**Comment by damithc** [comment]
@miffi Planned enhancements were meant to be enhancement to existing features rather than new features. So, if you feel the proposed enhancement is too different from an existing feature, it is grounds for not accepting it as a planned enhancement.
But if an acceptable enhancement (in the list of planned enhancements) to an existing feature X makes another feature Y obsolete, we'll have to accept that further enhancement to Y is not useful.

**Comment by miffi** [comment]
Alright, thanks prof. I think that it's too different, so I'll voice my concerns in the tester response.
