### ISSUE TITLE
Excessive Flagging of Duplications

### ISSUE THREAD

**Issue by tohlh** [nus-cs2103-AY2324S2/forum#978]
The team that I reviewed flagged a couple of my reported bugs as duplicates, even when their corresponding bugs are clearly not the same.

Since these bugs were wrongly flagged in the first place, and the team decided to only respond to one of the bugs (it is usually the other bug that they respond to, and they leave no comment on the one that I reported), is this considered as the team not providing any justification, and therefore their decision will be rejected by default?

**Comment by damithc** [comment]
@tohlh You can object to those duplicate flagging if you don't agree with the team's decision.
The teaching team will consider their response to the 'original' bug even if they did not provide a separate response to the 'duplicate'. If the latter was provided, we consider both responses in combination.

**Comment by jinhanfromNUS** [comment]
I think for your question, the decision made in the end whether a bug is a duplicate or not will be decided by the prof/TA team.

Not sure whether you noticed this. To increase your chance to _win_ in the battle of "whether this is a duplication", there is a section for you to place down your reasonings why you deem your bug is different from others.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111408810/718d656f-6926-413a-9bda-7d817568d1ab)

For more information regarding *duplicates*, please check [this](https://github.com/nus-cs2103-AY2122S2/forum/issues/254#issuecomment-1087582805)
