### ISSUE TITLE
Are undocumented features bugs?

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#988]
I thought of the following scenarios for undocumented features, but may I seek clarification or feedback if they are rightly accessed?

- Feature is non-trivial and works -> should be a bug since the user might reasonably benefit from it
- Feature is trivial and works -> unsure, hints towards dead code / possibly larger undocumented issues?
- Feature is broken -> unsure, depends on if the user can possibly run into it and crash by accident?

**Comment by damithc** [comment]
@yisiox If the said feature is not visible to the user and very unlikely for the user to detect it by accident, we can assume the feature was never meant to be released in the current version, which should be fine.
If the feature is simple, easily discoverable, and intuitive to use, it is fine to be omitted from the UG, especially if the inclusion seems adding noise rather than value.
Other cases point to some issue, either an omission in the UG, or a WIP feature not properly protected/hidden/disabled in the released product.
