### ISSUE TITLE
Is the Forking Workflow considered a DRCS or CRCS?

### ISSUE THREAD

**Issue by ThatGirlJam** [nus-cs2103-AY2324S2/forum#994]
Hi! Would forking workflow be classified under DRCS or CRCS?

Since it has a central repo (the main repo to be forked from) yet allows multiple remote repos in a way with the forked repos (and is using Git), would it belong under DRCS or CRCS? Or perhaps I'm understanding what DRCS/CRCS are wrongly?

**Comment by dillontkh** [comment]
~~I think the forking workflow, where **each team member has their own remote repository**, would classify under DRCS.~~

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/be664fc4-9b7d-4e79-b63d-290042c17491)

~~On the other hand, if all team members were pushing/pulling from a **single remote repo**, that would fall under CRCS.~~

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/80b27aee-33f9-4c31-9b1c-3715b5084536)

~~I do agree that it seems a little confusing, as the forking workflow has a 'main' repo that all the other remote repos refer to, but I think the fact that there are even multiple remote repos in the first place makes it fall under DRCS.~~

edit: this is wrong, refer to prof's response below

**Comment by damithc** [comment]
At the CRCS end of the spectrum, there are no local repositories (i.e., version history is not saved locally). Everyone connect to the one central repository to update their working copy of files or push their changes to the central repo.
When I was in the university, we used a software called CVS (there was no Git back then) that worked in that way. At the time most RCS software were like that, if not all.

The moment you have local repos (i.e., version history is saved locally as well), you are already moving towards DRCS (because you already have multiple copies of the repo). With multiple remote repos, you are even more DRCS. 

So, as long as you are using Git (which is considered a DRCS tool), you are technically in DRCS territory already, irrespective of the workflow used.

**Comment by dillontkh** [comment]
I see, thanks for the clarification prof!

**Comment by ThatGirlJam** [comment]
I see, thank you @dillontkh and @damithc !
