### ISSUE TITLE
Why is a new repo `pe-dev-reponse` created?

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#999]
Why not transfer the issues to the team's `tp` repo instead, just like in the PE dry run?

Is there a reason why a new repository is created just for phase 2?

**Comment by damithc** [comment]
Many reasons:
* we need more control for the PE e.g., everyone should get access to the bugs at the same time, 
* PE needs precise labels
* Bot needs higher privilege access to the repo
* Creating issues in other repos (not owned by the issue creator) is much slower due to GitHub throttling
* Not good to pollute a project repo issue tracker with issues of the PE
* etc.
